/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2017 at 12:02:23 AM China Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSURLSessionAppleIDContext <NSObject,NSCopying,NSSecureCoding>
@required
-(id)relevantHTTPStatusCodes;
-(void)URLSession:(id)arg1 task:(id)arg2 getAppleIDHeadersForResponse:(id)arg3 completionHandler:(/*^block*/id)arg4;

@end

