/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:27 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface AADelegateResponseStore : NSObject
+(void)saveiCloudResponseParameters:(id)arg1 ;
+(void)restoreFinished;
+(void)saveiCloudToken:(id)arg1 hsaToken:(id)arg2 fmipToken:(id)arg3 faceTimeToken:(id)arg4 madridToken:(id)arg5 gameCenterToken:(id)arg6 ;
+(id)responseAndTokenRuntimeStore;
+(void)_saveKeychainItem:(id)arg1 forUsername:(id)arg2 service:(id)arg3 itemDescription:(id)arg4 ;
@end

