/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:27 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_source;
@class ACAccountStore, AASetupAssistantService, NSArray, NSMutableArray, NSMutableDictionary, NSObject;

@interface AADelegateAccountSetupHelper : NSObject {

	ACAccountStore* _accountStore;
	AASetupAssistantService* _aaService;
	NSArray* _delegatesToSetup;
	NSMutableArray* _pendingCompletionBundles;
	NSMutableDictionary* _assistantDelegates;
	/*^block*/id _handler;
	NSObject*<OS_dispatch_source> _delegatetimer;

}
-(id)initWithStore:(id)arg1 ;
-(id)init;
-(void)_setupDelegateAccountsWithEmailChoice:(id)arg1 ;
-(id)_loadAssistantDelegateBundles;
-(void)_completeiCloudAndDelegateSetupWithResponse:(id)arg1 ;
-(id)_adjustResponseDictionary:(id)arg1 ;
-(void)setupiCloudDelegateWithUsername:(id)arg1 password:(id)arg2 emailChoice:(id)arg3 withHandler:(/*^block*/id)arg4 ;
@end

