/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:26 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppleAccount/AAResponse.h>

@class NSNumber, NSString;

@interface AAMobileMeOfferResponse : AAResponse

@property (nonatomic,readonly) NSNumber * identifier; 
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * message; 
@property (nonatomic,readonly) NSString * classicTitle; 
@property (nonatomic,readonly) NSString * classicMessage; 
-(NSNumber *)identifier;
-(NSString *)title;
-(NSString *)message;
-(NSString *)classicTitle;
-(NSString *)classicMessage;
@end

