/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:27 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MSSearchDelegate <NSObject>
@optional
-(char)search:(id)arg1 didFindResults:(id)arg2;
-(void)search:(id)arg1 didFinishWithError:(id)arg2;

@end

