//#import <StoreServices/StoreServices-Structs.h>
////#import <libobjc.A.dylib/SSRequestDelegate.h>
#import <StoreServices/SSKeyValueStore.h>
#import <StoreServices/SSURLBag.h>
@interface SSDevice : NSObject
+(id)copyCachedAvailableItemKinds;
+(BOOL)promptNeedsDisplay:(id)display ;
+(BOOL)setCachedAvailableItemKinds:(id)kinds ;
+(void)setLastPromptAttemptDate:(id)date forPromptWithIdentifier:(id)identifier ;
+(void)setPromptWithIdentifier:(id)identifier needsDisplay:(BOOL)display ;
+(id)currentDevice;
-(NSString *)uniqueDeviceIdentifier;
-(void)setStoreFrontIdentifier:(id)identifier accountIdentifier:(id)identifier2 isTransient:(BOOL)transient ;
-(NSString *)cloudMediaLibraryIdentifier;
-(NSString *)mediaLibraryIdentifier;
-(NSString *)softwareLibraryIdentifier;
-(void)_cacheKeyValueStoreValues;
-(BOOL)_getDeviceType:(unsigned*)type error:(id*)error ;
-(void)setStoreFrontIdentifier:(id)identifier isTransient:(BOOL)transient ;
-(id)_newLegacyUserAgent:(BOOL*)agent ;
-(id)_userAgentClientNameForInfoPlist:(id)plist ;
-(id)_userAgentClientVersionForInfoPlist:(id)plist clientName:(id)name ;
-(id)_newModernUserAgentWithClientName:(id)name version:(id)version isCachable:(BOOL*)cachable ;
-(id)_copyCarrierBundleEligibilityWithStatus:(id)status ;
-(long long)_deviceType;
-(void)_updateAutomaticDownloadKinds:(id)kinds withValue:(id)value completionBlock:(/*^block*/id)block ;
-(void)_invalidatePhoneNumber;
-(id)_copyProductType;
-(long long)_deviceTypeForProductType:(id)type ;
-(id)_productVersion;
-(void)_reloadAfterStoreFrontChange;
-(BOOL)_setStoreFrontIdentifier:(id)identifier isTransient:(BOOL)transient ;
-(void)_postStoreFrontDidChangeNotification;
-(void)_updateBatteryLevelFromService:(unsigned)service ;
-(void)_reloadPluggedInState;
-(BOOL)_is720pCapable;
-(BOOL)_is1080pCapable;
-(id)_userAgentClientNameForBundleID:(id)d ;
-(void)setStoreFrontIdentifier:(id)identifier account:(id)account isTransient:(BOOL)transient ;
-(long long)_deviceTypeForUnknownIPad:(id)pad ;
-(long long)_deviceTypeForUnknownIPhone:(id)phone ;
-(long long)_deviceTypeForUnknownIPod:(id)pod ;
-(long long)_deviceTypeForUnknownAppleTV:(id)v ;
-(int)_deviceClass;
-(int)_screenClass;
-(id)_diskCapacityString;
-(id)_fairPlayDeviceTypeString;
-(id)_appleTVProductVersion;
-(id)_userAgentClientNameForAppleTVBundleID:(id)d ;
-(id)copyStoreFrontRequestHeaders;
-(void)getAvailableItemKindsWithBlock:(/*^block*/id)block ;
-(void)getCellularNetworkingAllowedWithBlock:(/*^block*/id)block ;
-(void)sdk_loadStoreFrontIdentifier:(/*^block*/id)identifier ;
-(void)setCellularNetworkingAllowed:(BOOL)allowed ;
-(void)setStoreFrontWithResponseHeaders:(id)headers ;
-(void)showPromptWithIdentifier:(id)identifier completionHandler:(/*^block*/id)handler ;
-(NSString *)legacyUserAgent;
-(id)carrierBundleStatusForService:(long long)service ;
-(void)getCarrierBundleStatusForService:(long long)service completionHandler:(/*^block*/id)handler ;
-(void)enableAllAutomaticDownloadKindsWithCompletionBlock:(/*^block*/id)block ;
-(void)minusAutomaticDownloadKinds:(id)kinds withCompletionBlock:(/*^block*/id)block ;
-(void)setCloudMediaLibraryIdentifier:(NSString *)identifier ;
-(void)setMediaLibraryIdentifier:(NSString *)identifier ;
-(void)startPowerMonitoring;
-(void)stopPowerMonitoring;
-(void)synchronizeAutomaticDownloadKinds;
-(void)unionAutomaticDownloadKinds:(id)kinds withCompletionBlock:(/*^block*/id)block ;
-(id)userAgentWithBundleIdentifier:(id)identifier version:(id)version ;
-(void)resetStoreFrontForSignOut;
-(id)_copyKeyValueStoreValueForDomain:(id)domain key:(id)key ;
-(void)_invalidateSoftwareCUID;
-(id)init;
-(void)dealloc;
-(NSString *)phoneNumber;
-(double)batteryLevel;
-(NSString *)userAgent;
-(BOOL)supportsDeviceCapability:(long long)capability ;
-(id)userAgentWithClientName:(id)name version:(id)version ;
-(BOOL)isPluggedIn;
-(void)setSoftwareLibraryIdentifier:(NSString *)identifier ;
-(BOOL)getMachineIdentifier:(id*)identifier otp:(id*)otp forAccountIdentifier:(id)identifier3 ;
-(void)setAutomaticDownloadKinds:(id)kinds withCompletionBlock:(/*^block*/id)block ;
-(NSSet *)automaticDownloadKinds;
-(unsigned)deviceTypeIdentifier;
-(void)reloadStoreFrontIdentifier;
-(BOOL)isStoreFrontIdentifierTransient;
-(NSString *)synchedStoreFrontIdentifier;
-(NSString *)thinnedApplicationVariantIdentifier;
-(NSString *)compatibleProductType;
-(NSString *)serialNumber;
-(NSString *)storeFrontIdentifier;
-(NSString *)productType;
-(long long)deviceType;
-(NSString *)productVersion;
-(void)loadStoreFrontWithCompletionHandler:(/*^block*/id)handler ;
@end
