////#import <libobjc.A.dylib/ASDJobManagerObserver.h>
#import <StoreServices/SSXPCConnection.h>
#import <StoreServices/SSDownloadManagerOptions.h>
@interface SSDownloadManager : NSObject
+(void)_sendGlobalHandler:(id)handler ;
+(void)reconnectToLSApplicationWorkspace;
+(void)removePersistenceIdentifier:(id)identifier ;
+(void)setDownloadHandler:(id)handler ;
+(id)EBookDownloadManager;
+(id)softwareDownloadManager;
+(void)reevaluateBackgroundDownloadsForBundleIdentifiers:(id)identifiers ;
+(void)_triggerDownloads;
+(id)IPodDownloadKinds;
+(id)softwareDownloadKinds;
+(id)EBookDownloadKinds;
+(void)retryAllRestoreDownloads;
+(id)allStoreDownloadKinds;
+(id)IPodDownloadManager;
+(id)ITunesDownloadKinds;
-(id)initWithDownloadKinds:(id)kinds ;
-(BOOL)canCancelDownload:(id)download ;
-(void)_handleDownloadsRemoved:(id)removed ;
-(void)_willFinishDownloads:(id)downloads ;
-(void)_finishDownloads:(id)downloads ;
-(id)_XPCConnection;
-(void)_connectAfterDaemonLaunch;
-(id)_initSSDownloadManager;
-(BOOL)_supportsSoftwareKind;
-(void)_addAppstoredOptions;
-(void)_startJobManager;
-(void)_connectAsObserver;
-(id)_copyDownloadsForMessage:(long long)message downloadIDs:(id)ds ;
-(void)_insertDownloads:(id)downloads before:(id)before after:(id)after completionBlock:(/*^block*/id)block ;
-(void)_sendMessage:(id)message withCompletionBlock:(/*^block*/id)block ;
-(id)_filterJobIDsFromDownloads:(void** /* inout id* */)downloads ;
-(id)_copyDownloads;
-(id)_filterJobsFromDownloads:(void** /* inout id* */)downloads ;
-(void)_moveDownload:(id)download before:(id)before after:(id)after completionBlock:(/*^block*/id)block ;
-(void)_pauseDownloads:(id)downloads forced:(BOOL)forced completionBlock:(/*^block*/id)block ;
-(void)setDownloads:(id)downloads forKinds:(id)kinds completionBlock:(/*^block*/id)block ;
-(void)_handleReply:(id)reply forDownloads:(id)downloads message:(id)message isRetry:(BOOL)retry block:(/*^block*/id)block ;
-(void)_sendObserverConnection;
-(void)_loadDownloadKindsUsingNetwork;
-(void)_handleMessage:(id)message fromServerConnection:(id)connection ;
-(void)_checkDownloadsForDiversions:(id)diversions ;
-(void)_reloadIsUsingNetworkWithDownloadKinds:(id)kinds ;
-(void)_sendDownloadsChanged:(id)changed ;
-(void)_handleDownloadKindsUsingNetworkChanged:(id)changed ;
-(void)_handleDownloadsChanged:(id)changed ;
-(void)_handleDownloadStatesChanged:(id)changed ;
-(id)_copyDownloadKindsUsingNetwork;
-(void)_sendMessageToObservers:(SEL)observers ;
-(id)_newOptionsDictionary;
-(id)_downloadsForJobs:(id)jobs ;
-(void)cancelAllDownloadsWithCompletionBlock:(/*^block*/id)block ;
-(void)insertDownloads:(id)downloads beforeDownload:(id)download completionBlock:(/*^block*/id)block ;
-(void)moveDownload:(id)download beforeDownload:(id)download2 completionBlock:(/*^block*/id)block ;
-(void)setDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)_pauseDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)dealloc;
-(void)addObserver:(id)observer ;
-(void)removeObserver:(id)observer ;
-(NSArray *)activeDownloads;
-(BOOL)isUsingNetwork;
-(void)finishDownloads:(id)downloads ;
-(void)pauseDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)resumeDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)restartDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)moveDownload:(id)download afterDownload:(id)download2 completionBlock:(/*^block*/id)block ;
-(SSDownloadManagerOptions *)managerOptions;
-(id)initWithManagerOptions:(id)options ;
-(id)_jobManager;
-(void)cancelDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)getDownloadsUsingBlock:(/*^block*/id)block ;
-(void)insertDownloads:(id)downloads afterDownload:(id)download completionBlock:(/*^block*/id)block ;
-(void)reloadFromServer;
-(void)addDownloads:(id)downloads completionBlock:(/*^block*/id)block ;
-(void)jobManager:(id)manager changedJobs:(id)jobs ;
-(void)jobManager:(id)manager updatedProgressOfJobs:(id)jobs ;
-(void)jobManager:(id)manager updatedStateOfJobs:(id)jobs ;
-(NSArray *)downloads;
@end
