#import <StoreServices/SSMetricsMutableEvent.h>
@interface SSMetricsLoadURLEvent : SSMetricsMutableEvent
+(id)_bagPerformanceValues;
+(BOOL)shouldReportCachedEvent;
+(id)_bagValueForKey:(id)key ;
+(id)_timingMetricsWindowStartTime;
+(double)_randomDouble;
+(void)_setTimingMetricsWindowStartTime:(id)time ;
+(BOOL)shouldCollectTimingData;
+(BOOL)shouldLogTimingMetrics;
-(double)connectionEndTime;
-(void)setConnectionEndTime:(double)time ;
-(double)connectionStartTime;
-(void)setConnectionStartTime:(double)time ;
-(unsigned long long)connectionStartNStatRXBytes;
-(void)setConnectionStartNStatRXBytes:(unsigned long long)bytes ;
-(unsigned long long)connectionStartNStatTXBytes;
-(void)setConnectionStartNStatTXBytes:(unsigned long long)bytes ;
-(unsigned long long)connectionStopNStatRXBytes;
-(void)setConnectionStopNStatRXBytes:(unsigned long long)bytes ;
-(unsigned long long)connectionStopNStatTXBytes;
-(void)setConnectionStopNStatTXBytes:(unsigned long long)bytes ;
-(double)domainLookupEndTime;
-(void)setDomainLookupEndTime:(double)time ;
-(double)domainLookupStartTime;
-(void)setDomainLookupStartTime:(double)time ;
-(void)setFetchStartTime:(double)time ;
-(double)redirectEndTime;
-(void)setRedirectEndTime:(double)time ;
-(double)redirectStartTime;
-(void)setRedirectStartTime:(double)time ;
-(double)secureConnectionStartTime;
-(void)setSecureConnectionStartTime:(double)time ;
-(double)xpSamplingPercentageCachedResponses;
-(void)setXPSamplingPercentageCachedResponses:(double)responses ;
-(void)setDNSServers:(NSString *)servers ;
-(void)setRequestURL:(NSString *)l ;
-(void)setResolvedIPAddress:(NSString *)address ;
-(NSString *)requestURL;
-(NSString *)DNSServers;
-(NSString *)resolvedIPAddress;
-(id)init;
-(id)description;
-(long long)statusCode;
-(NSString *)connectionType;
-(void)setConnectionType:(NSString *)type ;
-(void)setStatusCode:(long long)code ;
-(void)setRedirectCount:(unsigned long long)count ;
-(unsigned long long)redirectCount;
-(void)setConnectionReused:(BOOL)reused ;
-(BOOL)connectionReused;
-(double)requestStartTime;
-(double)responseStartTime;
-(double)responseEndTime;
-(void)setXPSessionDuration:(double)duration ;
-(void)setXPSamplingPercentageUsers:(double)users ;
-(void)setXPSamplingForced:(BOOL)forced ;
-(double)xpSessionDuration;
-(BOOL)xpSamplingForced;
-(double)xpSamplingPercentageUsers;
-(void)setClientCorrelationKey:(NSString *)key ;
-(NSString *)clientCorrelationKey;
-(void)setRequestStartTime:(double)time ;
-(void)setResponseStartTime:(double)time ;
-(void)setResponseEndTime:(double)time ;
-(double)fetchStartTime;
@end
