/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:55:59 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UIBasicAnimationFactory <NSObject>
@optional
-(id)_timingFunctionForAnimation;
-(id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;

@required
-(id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end

