/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:04 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKStoreProductViewControllerDelegatePrivate <SKStoreProductViewControllerDelegate>
@optional
-(void)productViewController:(id)arg1 didFinishWithResult:(long long)arg2;
-(void)productViewController:(id)arg1 presentProductWithRequest:(id)arg2 animated:(BOOL)arg3;

@end

