/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:55:59 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SUMenuViewControllerDelegate <NSObject>
@optional
-(void)menuViewController:(id)arg1 didTapButton:(id)arg2;
-(void)menuViewControllerDidCancel:(id)arg1;
-(void)menuViewController:(id)arg1 didSelectItemAtIndex:(long long)arg2;

@end

