/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:00 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SULockoutViewController.h>

@interface SUNetworkLockoutViewController : SULockoutViewController
-(id)init;
-(void)loadView;
-(void)setSection:(id)arg1 ;
-(void)setLocalizationBundle:(id)arg1 ;
-(void)_reloadUserInterface;
@end

