/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:55:59 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SUPreviewOverlayContainer <NSObject>
@optional
-(BOOL)isShowingPreviewOverlay;
-(void)hidePreviewOverlay:(id)arg1 animated:(BOOL)arg2 completionBlock:(/*^block*/id)arg3;
-(BOOL)showPreviewOverlay:(id)arg1 animated:(BOOL)arg2 completionBlock:(/*^block*/id)arg3;

@end

