/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:00 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SUPurchaseAnimator : NSObject
+(void)performHopAnimationForView:(id)arg1 relativeToView:(id)arg2 tabBarController:(id)arg3 finalAlpha:(float)arg4 scale:(float)arg5 ;
+(void)performHopAnimationForView:(id)arg1 relativeToView:(id)arg2 finalAlpha:(float)arg3 scale:(float)arg4 ;
@end

