/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:04 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptObject.h>

@class NSDictionary, NSString;

@interface SUScriptFacebookFriend : SUScriptObject {

	NSDictionary* _dictionary;

}

@property (readonly) NSString * identifier; 
@property (readonly) NSString * name; 
+(void)initialize;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(void)dealloc;
-(NSString *)name;
-(NSString *)identifier;
-(id)initWithName:(id)arg1 ;
-(id)attributeKeys;
-(id)initWithFriendDictionary:(id)arg1 ;
-(id)scriptAttributeKeys;
-(id)_className;
@end

