/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:02 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptViewController.h>

@class SUScriptReview;

@interface SUScriptComposeReviewViewController : SUScriptViewController

@property (readonly) SUScriptReview * review; 
+(id)webScriptNameForKey:(const char*)arg1 ;
-(id)init;
-(id)attributeKeys;
-(void)setReview:(SUScriptReview *)arg1 ;
-(SUScriptReview *)review;
-(id)newNativeViewController;
-(id)initWithScriptReview:(id)arg1 clientInterface:(id)arg2 ;
-(id)scriptAttributeKeys;
-(id)_className;
@end

