/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:02 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptViewController.h>

@class NSNumber;

@interface SUScriptReportAProblemViewController : SUScriptViewController

@property (readonly) NSNumber * adamID; 
+(void)initialize;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(id)init;
-(id)attributeKeys;
-(NSNumber *)adamID;
-(id)newNativeViewController;
-(id)initWithAdamID:(id)arg1 clientInterface:(id)arg2 ;
-(void)setAdamID:(NSNumber *)arg1 ;
-(id)scriptAttributeKeys;
-(id)_className;
@end

