/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:01 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SUScriptModalDialogResponse : NSObject {

	long long _buttonIndex;
	NSString* _textFieldValue;

}

@property (assign,nonatomic) long long buttonIndex;                  //@synthesize buttonIndex=_buttonIndex - In the implementation block
@property (nonatomic,retain) NSString * textFieldValue;              //@synthesize textFieldValue=_textFieldValue - In the implementation block
-(void)dealloc;
-(long long)buttonIndex;
-(NSString *)textFieldValue;
-(void)setTextFieldValue:(NSString *)arg1 ;
-(void)setButtonIndex:(long long)arg1 ;
@end

