/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:02 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class WebScriptObject, NSLock, SUScriptObject;

@interface SUScriptFunction : NSObject {

	WebScriptObject* _function;
	NSLock* _lock;
	SUScriptObject* _thisObject;

}

@property (retain) WebScriptObject * scriptObject; 
@property (__weak) id thisObject; 
-(void)dealloc;
-(id)init;
-(void)lock;
-(void)unlock;
-(id)initWithScriptObject:(id)arg1 ;
-(void)setThisObject:(id)arg1 ;
-(WebScriptObject *)scriptObject;
-(void)setScriptObject:(WebScriptObject *)arg1 ;
-(id)callSynchronouslyWithArguments:(id)arg1 ;
-(BOOL)callWithArguments:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)_copyAdjustedArgumentsForArguments:(id)arg1 ;
-(id)thisObject;
-(BOOL)callWithArguments:(id)arg1 ;
@end

