/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:02 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptViewController.h>

@class NSArray, NSString;

@interface SUScriptMediaPickerController : SUScriptViewController

@property (assign) BOOL allowsPickingMultipleItems; 
@property (readonly) NSArray * mediaTypes; 
@property (retain) NSString * prompt; 
+(void)initialize;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(NSString *)prompt;
-(void)setPrompt:(NSString *)arg1 ;
-(NSArray *)mediaTypes;
-(id)attributeKeys;
-(BOOL)allowsPickingMultipleItems;
-(void)setAllowsPickingMultipleItems:(BOOL)arg1 ;
-(void)setNativeViewController:(id)arg1 ;
-(id)newNativeViewController;
-(id)scriptAttributeKeys;
-(id)_className;
-(id)initWithMediaTypes:(id)arg1 ;
@end

