/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:02 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptStorePageViewController.h>

@class NSString;

@interface SUScriptAccountPageViewController : SUScriptStorePageViewController

@property (retain) NSString * style; 
@property (readonly) NSString * styleNameDefault; 
@property (readonly) NSString * styleNameSignUp; 
@property (readonly) NSString * styleNameViewAccount; 
+(void)initialize;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(NSString *)style;
-(void)setStyle:(NSString *)arg1 ;
-(id)attributeKeys;
-(id)newNativeViewController;
-(NSString *)styleNameSignUp;
-(NSString *)styleNameViewAccount;
-(NSString *)styleNameDefault;
-(id)scriptAttributeKeys;
-(id)_className;
@end

