/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:55:59 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SUTableDataSource.h>

@class NSArray;

@interface SUSimpleTableDataSource : SUTableDataSource {

	Class _cellConfigurationClass;
	NSArray* _objects;

}

@property (nonatomic,retain) Class cellConfigurationClass;              //@synthesize cellConfigurationClass=_cellConfigurationClass - In the implementation block
@property (nonatomic,retain) NSArray * objects;                         //@synthesize objects=_objects - In the implementation block
-(void)dealloc;
-(long long)numberOfRowsInSection:(long long)arg1 ;
-(long long)numberOfSections;
-(double)cellHeightForIndexPath:(id)arg1 ;
-(void)reloadCellContexts;
-(id)objectForIndexPath:(id)arg1 ;
-(Class)cellConfigurationClass;
-(void)setCellConfigurationClass:(Class)arg1 ;
-(id)cellForIndexPath:(id)arg1 ;
-(NSArray *)objects;
-(void)configureCell:(id)arg1 forIndexPath:(id)arg2 ;
-(void)setObjects:(NSArray *)arg1 ;
@end

