/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:55:59 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStoreUI/SURotationController.h>

@class SURotationController, SUViewController;

@interface SUStorePageRotationController : SURotationController {

	SURotationController* _childRotationController;
	SUViewController* _childViewController;

}
-(void)dealloc;
-(void)finishRotationFromInterfaceOrientation:(long long)arg1 ;
-(void)animateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)prepareToRotateToInterfaceOrientation:(long long)arg1 ;
-(id)_childRotationController;
@end

