/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:03 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableView.h>

@interface SUTableView : UITableView {

	BOOL _allowsHeaderAndFooterToFloat;

}

@property (assign,nonatomic) BOOL allowsHeaderAndFooterToFloat;              //@synthesize allowsHeaderAndFooterToFloat=_allowsHeaderAndFooterToFloat - In the implementation block
-(BOOL)allowsHeaderViewsToFloat;
-(BOOL)allowsFooterViewsToFloat;
-(void)setAllowsHeaderAndFooterToFloat:(BOOL)arg1 ;
-(BOOL)allowsHeaderAndFooterToFloat;
@end

