/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2017 at 11:56:01 PM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SUViewControllerFactory : NSObject
-(id)newViewControllerForPage:(id)arg1 ofType:(long long)arg2 ;
-(id)newNetworkLockoutViewControllerWithSection:(id)arg1 ;
-(id)newComposeReviewViewControllerWithCompositionURL:(id)arg1 ;
-(id)newDownloadsViewController;
-(id)newViewControllerForTrackList:(id)arg1 ;
-(id)newVolumeViewController;
-(id)newPlaceholderViewController;
-(id)newStorePageViewControllerWithSection:(id)arg1 ;
@end

