/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:45 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class NSURL, NSString, NSDictionary;

@interface LSOpenOperation : NSOperation {

	char _executing;
	char _finished;
	char _sourceIsManaged;
	NSURL* _resourceURL;
	NSString* _applicationIdentifier;
	NSString* _documentIdentifier;
	id _userInfoPlist;
	NSDictionary* _options;
	id _delegate;
	int _result;

}
-(id)initForOpeningResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 sourceIsManaged:(char)arg4 userInfo:(id)arg5 options:(id)arg6 delegate:(id)arg7 ;
-(char)didSucceed;
-(void)completeOperation;
-(void)dealloc;
-(void)start;
-(void)main;
-(char)isFinished;
-(char)isExecuting;
-(char)isConcurrent;
@end

