/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:45 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCoreServices/LSUserActivityClientResponseProtocol.h>


@interface LSUserActivityManager : NSObject <LSUserActivityClientResponseProtocol> {

	NSXPCConnection* _connection;
	char _connectionInitializationSucceeded;
	char _needToSendInitialMessage;
	NSMapTable* _userActivitiesByUUID;
	char _supportsActivityContinuation;
	char _activityContinuationIsEnabled;
	NSUUID* _activeUserActivityUUID;

}

@property (retain,readonly) NSXPCConnection * connection; 
@property (copy) NSUUID * activeUserActivityUUID;                       //@synthesize activeUserActivityUUID=_activeUserActivityUUID - In the implementation block
@property (readonly) char supportsActivityContinuation;                 //@synthesize supportsActivityContinuation=_supportsActivityContinuation - In the implementation block
@property (readonly) char activityContinuationIsEnabled; 
@property (retain) NSMapTable * userActivitiesByUUID;                   //@synthesize userActivitiesByUUID=_userActivitiesByUUID - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)shouldSupportActivityContinuation;
+(char)userActivityContinuationSupported;
+(id)defaultManager;
-(void)sendInitialMessage;
-(NSMapTable *)userActivitiesByUUID;
-(void)setActiveUserActivityUUID:(NSUUID *)arg1 ;
-(id)_findUserActivityForUUID:(id)arg1 ;
-(void)addUserActivity:(id)arg1 ;
-(void)askClientUserActivityToSave:(id)arg1 ;
-(void)askClientUserActivityToSave:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)tellClientUserActivityItWasResumed:(id)arg1 ;
-(char)activityContinuationIsEnabled;
-(void)didReceiveInputStreamWithUUID:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3 ;
-(id)encodeUserActivity:(id)arg1 ;
-(id)createByDecodingUserActivity:(id)arg1 ;
-(char)supportsActivityContinuation;
-(void)setUserActivitiesByUUID:(NSMapTable *)arg1 ;
-(void)fetchUUID:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(void)markUserActivityAsDirty:(id)arg1 forceImmediate:(char)arg2 ;
-(char)userActivityIsActive:(id)arg1 ;
-(void)makeActive:(id)arg1 ;
-(void)makeInactive:(id)arg1 ;
-(void)removeUserActivity:(id)arg1 ;
-(NSUUID *)activeUserActivityUUID;
-(void)tellDaemonAboutNewLSUserActivity:(id)arg1 ;
-(void)sendUserActivityInfoToLSUserActivityd:(id)arg1 makeCurrent:(char)arg2 ;
-(void)dealloc;
-(id)init;
-(NSXPCConnection *)connection;
-(id)initWithConnection:(id)arg1 ;
@end

