/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:45 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCoreServices/LSBundleProxy.h>

@interface LSVPNPluginProxy : LSBundleProxy
+(id)VPNPluginProxyForIdentifier:(id)arg1 ;
-(id)_initWithBundleIdentifier:(id)arg1 ;
@end

