/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:50 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _NCWidgetViewController_Host_IPC
@required
-(void)__requestPreferredViewHeight:(float)arg1 usingAutolayout:(char)arg2 requestIdentifier:(id)arg3;
-(void)__requestLaunchOfURL:(id)arg1;
-(void)__closeTransactionForAppearanceCallWithState:(int)arg1 withIdentifier:(id)arg2;

@end

