/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:56 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class _SBFVibrantSettings;


@protocol _SBFVibrantView <NSObject>
@property (nonatomic,retain) _SBFVibrantSettings * vibrantSettings; 
@required
-(void)setBackgroundView:(id)arg1;
-(_SBFVibrantSettings *)vibrantSettings;
-(void)setVibrantSettings:(id)arg1;

@end

