/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/_UISettingsKeyObserver.h>
#import <SpringBoard/SBWallpaperObserver.h>

@class SBIconColorSettings, NSHashTable, NSString;

@interface _SBIconWallpaperColorProvider : NSObject <_UISettingsKeyObserver, SBWallpaperObserver> {

	SBIconColorSettings* _colorSettings;
	NSHashTable* _clients;
	CGColorRef _blurColor;
	CGColorRef _solidColor;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)wallpaperDidChangeForVariant:(int)arg1 ;
-(void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2 ;
-(void)wallpaperGeometryDidChangeForVariant:(int)arg1 ;
-(void)updateColorForClientBoundsChange:(id)arg1 ;
-(void)_updateClient:(id)arg1 ;
-(void)_updateBlurForClient:(id)arg1 ;
-(void)_updateAllClients;
-(void)_updateColors;
-(void)dealloc;
-(id)init;
-(void)addClient:(id)arg1 ;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2 ;
-(void)removeClient:(id)arg1 ;
@end

