/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIDynamicItem.h>

@class NSString;

@interface _SBNotificationCenterBouncingItem : NSObject <UIDynamicItem> {

	CGPoint _center;
	CGRect _bounds;
	/*^block*/id _stepper;

}

@property (assign,nonatomic) CGRect frame; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) CGPoint center; 
@property (nonatomic,readonly) CGRect bounds; 
@property (assign,nonatomic) CGAffineTransform transform; 
-(id)initWithFrame:(CGRect)arg1 stepper:(/*^block*/id)arg2 ;
-(void)dealloc;
-(CGRect)bounds;
-(void)setFrame:(CGRect)arg1 ;
-(CGRect)frame;
-(void)setBounds:(CGRect)arg1 ;
-(void)setTransform:(CGAffineTransform)arg1 ;
-(CGPoint)center;
-(CGAffineTransform)transform;
-(void)setCenter:(CGPoint)arg1 ;
@end

