/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:57 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _SBRemoteAlertHostViewControllerDelegate <NSObject>
@required
-(void)remoteAlertWantsToAllowBanners:(char)arg1;
-(void)remoteAlertDidTerminateWithError:(id)arg1;
-(void)remoteAlertWantsToLockUIAndDismiss;
-(void)remoteAlertWantsToUpdateAllowedHardwareButtonEvents:(int)arg1;
-(void)remoteAlertWantsWallpaperTunnelActive:(char)arg1;
-(void)remoteAlertWantsToSetBackgroundStyle:(int)arg1 withDuration:(double)arg2;
-(void)remoteAlertWantsMenuButtonDismissal:(char)arg1;
-(void)remoteAlertWantsToAllowAlertStacking:(char)arg1;
-(void)remoteAlertWantstoSetDismissalAnimationStyle:(int)arg1;
-(void)remoteAlertWantsToSetDesiredStatusBarStyleOverrides:(int)arg1;
-(void)remoteAlertWantsToSetIdleTimerDisabled:(char)arg1 forReason:(id)arg2;
-(void)remoteAlertWantsToSetAutoLockDuration:(double)arg1;
-(void)remoteAlertWantsToSetStatusBarHidden:(char)arg1 withDuration:(double)arg2;
-(void)remoteAlertWantsToDismissOnUILock:(char)arg1;
-(void)remoteAlertWantsToDisableFadeInAnimation:(char)arg1;
-(void)remoteAlertWantstoSetSupportedInterfaceOrientationOverride:(unsigned)arg1;

@end

