/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:53 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _UIActionSliderDelegate <NSObject>
@optional
-(void)actionSlider:(id)arg1 didUpdateSlideWithValue:(float)arg2;
-(void)actionSliderDidCompleteSlide:(id)arg1;
-(void)actionSliderDidCancelSlide:(id)arg1;
-(void)actionSliderDidBeginSlide:(id)arg1;

@end

