/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PGPictureInPictureControllerDelegate <NSObject>
@optional
-(void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2;
-(void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2;

@end

