/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIActivityContinuationAction.h>

@class NSDictionary, SBBestAppSuggestion;

@interface SBActivityContinuationAction : UIActivityContinuationAction {

	NSDictionary* _settings;
	long long launchSource;
	SBBestAppSuggestion* _appSuggestion;

}

@property (assign,nonatomic) long long launchSource; 
@property (nonatomic,retain) SBBestAppSuggestion * appSuggestion;              //@synthesize appSuggestion=_appSuggestion - In the implementation block
@property (nonatomic,__weak,readonly) NSDictionary * settings; 
-(SBBestAppSuggestion *)appSuggestion;
-(id)initWithIdentifier:(id)arg1 activityTypeIdentifier:(id)arg2 appSuggestion:(id)arg3 launchSource:(long long)arg4 ;
-(void)setLaunchSource:(long long)arg1 ;
-(void)setAppSuggestion:(SBBestAppSuggestion *)arg1 ;
-(NSDictionary *)settings;
-(long long)launchSource;
@end

