/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:04 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBAlertWindowViewControllerDelegate <NSObject>
@required
-(BOOL)defaultShouldAutorotateForAlertWindowViewController:(id)arg1;
-(long long)defaultInterfaceOrientationForPresentationOfAlertWindowViewController:(id)arg1;
-(unsigned long long)defaultSupportedInterfaceOrientationsForAlertWindowViewController:(id)arg1;

@end

