/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBApplicationServerDelegate <NSObject>
@required
-(void)applicationServer:(id)arg1 fetchWhitePointAdaptivityStyleForDisplayId:(unsigned)arg2 withCompletion:(/*^block*/id)arg3;
-(void)applicationServer:(id)arg1 fetchRemovabilityForBundleIdentifier:(id)arg2 withCompletion:(/*^block*/id)arg3;
-(void)applicationServer:(id)arg1 setRemovalAllowed:(BOOL)arg2 forBundleIdentifier:(id)arg3;
-(void)applicationServer:(id)arg1 fetchDynamicShortcutItemsForBundleIdentifier:(id)arg2 withCompletion:(/*^block*/id)arg3;
-(void)applicationServer:(id)arg1 setDynamicShortcutItems:(id)arg2 forBundleIdentifier:(id)arg3;

@end

