/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>
#import <SpringBoard/SBAppSwitcherPageContentView.h>

@protocol SBAppSwitcherCacheVended, FBWindowContextAppearance;
@class UIView, SBWallpaperEffectView, SBAppSwitcherStatusBarViewCache, SBRemoteAlertAdapter, FBWindowContextHostManager, NSString;

@interface SBAppSwitcherRemoteAlertContextHostWrapperView : UIView <SBAppSwitcherPageContentView> {

	UIView* _containerView;
	SBWallpaperEffectView* _wallpaperView;
	UIView*<SBAppSwitcherCacheVended> _fakeStatusBarView;
	SBAppSwitcherStatusBarViewCache* _statusBarCache;
	SBRemoteAlertAdapter* _remoteAlert;
	FBWindowContextHostManager* _contextHostManager;
	UIView*<FBWindowContextAppearance> _contextHostView;
	int _orientation;

}

@property (assign,nonatomic) int orientation;                       //@synthesize orientation=_orientation - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 remoteAlert:(id)arg2 statusBarCache:(id)arg3 contextHostManager:(id)arg4 ;
-(void)prepareToBecomeVisibleIfNecessary;
-(void)respondToBecomingInvisibleIfNecessary;
-(void)_layoutStatusBar;
-(CGAffineTransform)_rotationTransformForOrientation:(int)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(int)orientation;
-(void)didMoveToSuperview;
-(void)setOrientation:(int)arg1 ;
@end

