/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBApplicationShortcutMenuDelegate <NSObject>
@optional
-(void)applicationShortcutMenuDidDismiss:(id)arg1;
-(void)applicationShortcutMenuDidPresent:(id)arg1;

@required
-(void)applicationShortcutMenu:(id)arg1 activateShortcutItem:(id)arg2 index:(long long)arg3;
-(void)applicationShortcutMenu:(id)arg1 startEditingForIconView:(id)arg2;
-(void)applicationShortcutMenu:(id)arg1 launchApplicationWithIconView:(id)arg2;

@end

