/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSMutableDictionary, SBAppSwitcherDefaults, SBIconController;

@interface SBAppSwitcherModel : NSObject {

	NSMutableArray* _recentDisplayItems;
	NSMutableArray* _recentDisplayItemsForCommandTab;
	NSMutableDictionary* _displayItemsToRoles;
	SBAppSwitcherDefaults* _defaults;
	SBIconController* _iconController;

}
+(id)sharedInstance;
-(id)mainSwitcherDisplayItems;
-(id)commandTabDisplayItems;
-(void)addToFront:(id)arg1 role:(long long)arg2 ;
-(id)_recentsFromPrefs;
-(id)_displayItemRolesFromPrefsForLoadedDisplayItems:(id)arg1 ;
-(void)_saveRecents;
-(void)_appActivationStateDidChange:(id)arg1 ;
-(void)_warmUpRecentIcons;
-(id)initWithUserDefaults:(id)arg1 andIconController:(id)arg2 ;
-(id)_recentsFromLegacyPrefs;
-(void)_warmUpIconForDisplayItem:(id)arg1 ;
-(void)_pruneRoles;
-(id)displayItemsForAppsOfRoles:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)remove:(id)arg1 ;
@end

