/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBStatusBarAlphaChangeDelegate.h>

@class NSHashTable, NSMutableOrderedSet, NSMutableDictionary, NSMutableArray, NSMutableSet, XBStatusBarSettings, SBStatusBarAlphaChangeAssertion, NSString;

@interface SBAppStatusBarManager : NSObject <SBStatusBarAlphaChangeDelegate> {

	NSHashTable* _disableAlphaChangeAssertions;
	NSHashTable* _disableUserInteractionChangeAssertions;
	NSMutableOrderedSet* _statusBarAlphaLevels;
	NSMutableDictionary* _statusBarAlphaMap;
	NSMutableOrderedSet* _windowLevelOverrideReasons;
	NSMutableDictionary* _windowLevelOverrideMap;
	double _defaultWindowLevel;
	NSMutableDictionary* _edgeInsetsDictionary;
	NSMutableArray* _statusBarSettingsAssertionsByLevel[10];
	NSMutableSet* _activeLayoutLayers;
	XBStatusBarSettings* _currentStatusBarSettings;
	SBStatusBarAlphaChangeAssertion* _baseSettingsAlphaAssertion;

}

@property (nonatomic,readonly) UIEdgeInsets statusBarEdgeInsets; 
@property (nonatomic,readonly) unsigned long long topmostActiveLayoutLayer; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(UIEdgeInsets)statusBarEdgeInsets;
-(void)setStatusBarEdgeInsets:(UIEdgeInsets)arg1 forLayoutLayer:(unsigned long long)arg2 ;
-(void)removeActiveLayoutLayer:(unsigned long long)arg1 ;
-(void)addActiveLayoutLayer:(unsigned long long)arg1 ;
-(void)_addStatusBarSettingsAssertion:(id)arg1 ;
-(void)_removeStatusBarSettingsAssertion:(id)arg1 ;
-(void)willTransitionToSpringBoard;
-(void)didTransitionFromSpringBoard;
-(void)statusBarAlphaAssertionCreated:(id)arg1 ;
-(void)statusBarAlphaAssertionDidInvalidate:(id)arg1 ;
-(void)statusBarAlphaDidChangeForAssertion:(id)arg1 ;
-(void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1 ;
-(void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1 ;
-(void)_addDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1 ;
-(void)_removeDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1 ;
-(void)_cleanUpAllStatusBarSettingsAssertions;
-(void)_evaluateSettings;
-(void)hideStatusBarAtLevel:(unsigned long long)arg1 ;
-(void)showStatusBarAtLevel:(unsigned long long)arg1 ;
-(id)_descriptionForPropertyWithAssertions:(id)arg1 ;
-(void)_setStatusBarValueForPropertyWithAssertions:(id)arg1 setter:(/*^block*/id)arg2 ;
-(void)_changeStatusBarShowing:(BOOL)arg1 atLevel:(unsigned long long)arg2 ;
-(void)_updateWindowLevel;
-(id)_activeAssertion;
-(void)setStatusBarAlpha:(double)arg1 ;
-(void)_addAssertion:(id)arg1 toAssertions:(id)arg2 ;
-(void)_removeAssertion:(id)arg1 fromAssertions:(id)arg2 ;
-(void)_applyEdgeInsetsToStatusBar;
-(unsigned long long)topmostActiveLayoutLayer;
-(void)setStatusBarUserInteractionEnabled:(BOOL)arg1 ;
-(BOOL)isStatusBarUserInteractionEnabled;
-(void)setWindowLevel:(double)arg1 forOverrideReason:(id)arg2 ;
-(void)removeWindowLevelOverrideReason:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isStatusBarHidden;
-(void)setDefaultWindowLevel:(double)arg1 ;
@end

