/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:59 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBAppSwitcherPeopleDataSourceConsumer;
@interface SBAppSwitcherPeopleAbstractDataSource : NSObject {

	id<SBAppSwitcherPeopleDataSourceConsumer> _consumer;

}

@property (assign,nonatomic) id<SBAppSwitcherPeopleDataSourceConsumer> consumer;              //@synthesize consumer=_consumer - In the implementation block
-(void)updateIfNecessary;
-(id)_contactActionsForPerson:(void*)arg1 ;
-(id)_callActionsFromPerson:(void*)arg1 ;
-(char)hasiMessageCapability;
-(id)_contactActionOfType:(unsigned)arg1 forPerson:(void*)arg2 ;
-(char)hasCellularTelephonyCapability;
-(char)hasSMSCapability;
-(id<SBAppSwitcherPeopleDataSourceConsumer>)consumer;
-(void)setConsumer:(id<SBAppSwitcherPeopleDataSourceConsumer>)arg1 ;
@end

