/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:47 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString;


@protocol SBApplicationTerminationAssertion <NSObject>
@property (nonatomic,copy,readonly) NSString * displayId; 
@property (nonatomic,readonly) unsigned char reason; 
@required
-(NSString *)displayId;
-(unsigned char)reason;

@end

