/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBBaseSoftwareUpdateAlertItem.h>

@interface SBBaseSoftwareUpdateInstallFailureAlertItem : SBBaseSoftwareUpdateAlertItem {

	BOOL _actionTaken;

}

@property (assign,nonatomic) BOOL actionTaken;              //@synthesize actionTaken=_actionTaken - In the implementation block
-(BOOL)actionTaken;
-(void)setActionTaken:(BOOL)arg1 ;
-(void)willDeactivateForReason:(int)arg1 ;
-(BOOL)allowInSetup;
@end

