/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:47 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBBoundLayoutConstraint.h>

@interface SBBaselineBoundLayoutConstraint : SBBoundLayoutConstraint {

	float _baselineConstant;

}
+(id)constraintWithItem:(id)arg1 attribute:(int)arg2 relatedBy:(int)arg3 toItem:(id)arg4 attribute:(int)arg5 textAttributesObject:(id)arg6 keyPath:(id)arg7 baselineConstant:(float)arg8 ;
-(void)_boundValueDidChange;
@end

