/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIFetchContentInBackgroundAction, NSString;

@interface SBBackgroundFetchExternalRequest : NSObject {

	int _sequenceNumber;
	UIFetchContentInBackgroundAction* _action;
	NSString* _bundleID;

}

@property (nonatomic,retain) UIFetchContentInBackgroundAction * action;              //@synthesize action=_action - In the implementation block
@property (assign,nonatomic) int sequenceNumber;                                     //@synthesize sequenceNumber=_sequenceNumber - In the implementation block
@property (nonatomic,copy) NSString * bundleID;                                      //@synthesize bundleID=_bundleID - In the implementation block
-(id)initForBundleID:(id)arg1 ;
-(UIFetchContentInBackgroundAction *)action;
-(void)setAction:(UIFetchContentInBackgroundAction *)arg1 ;
-(int)sequenceNumber;
-(void)setSequenceNumber:(int)arg1 ;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(void)execute;
@end

