/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class SBBBSectionInfo, SBBBBulletinInfo;

@interface SBBBInfoOperand : NSObject {

	SBBBSectionInfo* _section;
	SBBBBulletinInfo* _bulletin;

}

@property (nonatomic,readonly) SBBBSectionInfo * section;                                //@synthesize section=_section - In the implementation block
@property (nonatomic,readonly) SBBBBulletinInfo * bulletin;                              //@synthesize bulletin=_bulletin - In the implementation block
@property (getter=isSectionOperand,nonatomic,readonly) char sectionOperand; 
+(id)operandWithSection:(id)arg1 bulletin:(id)arg2 ;
-(char)isSectionOperand;
-(id)initWithSection:(id)arg1 bulletin:(id)arg2 ;
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(SBBBSectionInfo *)section;
-(SBBBBulletinInfo *)bulletin;
@end

