/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@interface SBBrightnessController : NSObject {

	BOOL _debounce;
	BKSDisplayBrightnessTransactionRef _brightnessDownTransaction;
	BKSDisplayBrightnessTransactionRef _brightnessUpTransaction;

}
+(id)sharedBrightnessController;
-(void)handleBrightnessEvent:(IOHIDEventRef)arg1 ;
-(void)cancelBrightnessEvent;
-(float)_calcButtonRepeatDelay;
-(void)_setBrightnessLevel:(float)arg1 showHUD:(BOOL)arg2 ;
-(void)increaseBrightnessAndRepeat;
-(void)adjustBacklightLevel:(BOOL)arg1 ;
-(void)decreaseBrightnessAndRepeat;
-(void)setBrightnessLevel:(float)arg1 ;
@end

