/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:47 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBBulletinViewControllerDelegate <NSObject>
@optional
-(char)bulletinViewController:(id)arg1 didSelectAction:(id)arg2 forBulletin:(id)arg3 inSection:(id)arg4;
-(int)bulletinViewController:(id)arg1 insertionAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(int)bulletinViewController:(id)arg1 removalAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(int)bulletinViewController:(id)arg1 replacementAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(char)bulletinViewController:(id)arg1 shouldHighlightBulletin:(id)arg2 inSection:(id)arg3;
-(char)bulletinViewController:(id)arg1 didSelectBulletin:(id)arg2 inSection:(id)arg3;
-(int)layoutModeForBulletinViewController:(id)arg1;

@end

