/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/_UISettings.h>

@interface SBCarDisplaySettings : _UISettings {

	BOOL _animateLockOutModeChanges;
	long long _lockOutMode;

}

@property (assign) BOOL animateLockOutModeChanges;              //@synthesize animateLockOutModeChanges=_animateLockOutModeChanges - In the implementation block
@property (assign) long long lockOutMode;                       //@synthesize lockOutMode=_lockOutMode - In the implementation block
+(id)settingsControllerModule;
-(BOOL)animateLockOutModeChanges;
-(long long)lockOutMode;
-(void)setLockOutMode:(long long)arg1 ;
-(void)setAnimateLockOutModeChanges:(BOOL)arg1 ;
-(void)setDefaultValues;
@end

