/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:57 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBSceneLayoutManager.h>

@protocol SBStarkSessionConfiguring;
@interface SBCarDisplaySceneLayoutManager : SBSceneLayoutManager {

	id<SBStarkSessionConfiguring> _configuration;

}
-(CGRect)frameForDisplayItem:(id)arg1 inLayout:(id)arg2 ;
-(id)initWithManager:(id)arg1 configuration:(id)arg2 ;
-(void)dealloc;
@end

