/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:47 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@class NSString;

@interface SBCellDataActivationFailureAlertItem : SBAlertItem {

	int _error;
	NSString* _reason;
	char _suggestWiFi;
	int _settingsButtonIndex;

}
-(id)initWithErrorCode:(int)arg1 reason:(id)arg2 suggestWiFi:(char)arg3 ;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(char)dismissOnLock;
-(void)configure:(char)arg1 requirePasscodeForActions:(char)arg2 ;
-(void)_showNetworkPrefs;
@end

