/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/UNSNotificationSchedulerDelegate.h>

@class UNSNotificationScheduler, NSString;

@interface SBClockNotificationManager : NSObject <UNSNotificationSchedulerDelegate> {

	UNSNotificationScheduler* _notificationScheduler;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)cancelScheduledLocalNotification:(id)arg1 ;
-(void)snoozeScheduledLocalNotification:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)scheduledLocalNotificationsWithResult:(/*^block*/id)arg1 ;
-(id)init;
-(id)scheduledLocalNotifications;
-(void)notificationScheduler:(id)arg1 didFireLocalNotifications:(id)arg2 ;
-(void)notificationScheduler:(id)arg1 didChangeScheduledLocalNotifications:(id)arg2 ;
@end

