/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBScene, FBSSceneClientSettings, FBSSceneTransitionContext;

@interface SBClientSettingObserverContext : NSObject {

	FBScene* _scene;
	FBSSceneClientSettings* _oldClientSettings;
	FBSSceneTransitionContext* _transition;

}

@property (nonatomic,retain) FBScene * scene;                                         //@synthesize scene=_scene - In the implementation block
@property (nonatomic,retain) FBSSceneClientSettings * oldClientSettings;              //@synthesize oldClientSettings=_oldClientSettings - In the implementation block
@property (nonatomic,retain) FBSSceneTransitionContext * transition;                  //@synthesize transition=_transition - In the implementation block
-(void)setOldClientSettings:(FBSSceneClientSettings *)arg1 ;
-(FBSSceneClientSettings *)oldClientSettings;
-(void)setTransition:(FBSSceneTransitionContext *)arg1 ;
-(FBSSceneTransitionContext *)transition;
-(FBScene *)scene;
-(void)setScene:(FBScene *)arg1 ;
@end

