/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBControlCenterViewControllerDelegate <NSObject>
@required
-(void)controlCenterViewControllerWantsDismissal:(id)arg1;
-(BOOL)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2;
-(void)controlCenterViewController:(id)arg1 handleTap:(id)arg2;
-(void)controlCenterViewController:(id)arg1 handlePan:(id)arg2;
-(void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2;

@end

