/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSCountedSet, NSMutableDictionary;

@interface SBCountedMap : NSObject {

	NSCountedSet* _countedKeys;
	NSMutableDictionary* _map;

}
-(void)checkinValue:(id)arg1 ;
-(id)checkoutValueForKey:(id)arg1 creationBlock:(/*^block*/id)arg2 ;
-(void)checkinValues:(id)arg1 ;
-(id)init;
@end

