/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardUI/SBUIControlCenterButton.h>

@class NSString, NSNumber;

@interface SBControlCenterButton : SBUIControlCenterButton {

	NSString* _identifier;
	NSNumber* _sortKey;

}

@property (nonatomic,copy) NSString * identifier;              //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,copy) NSNumber * sortKey;                 //@synthesize sortKey=_sortKey - In the implementation block
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setSortKey:(NSNumber *)arg1 ;
-(void)_updateForStateChange;
-(NSNumber *)sortKey;
@end

