/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSSet, NSDictionary;

@interface SBComposedWallpaperSpecificationLayer : NSObject

@property (nonatomic,copy,readonly) NSSet * referencedAssetURLs; 
@property (nonatomic,copy,readonly) NSDictionary * propertyListRepresentation; 
-(id)initWithLayerDictionary:(id)arg1 ;
-(NSSet *)referencedAssetURLs;
-(NSDictionary *)propertyListRepresentation;
@end

