/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBComposedWallpaperSpecificationLayer.h>

@class UIColor;

@interface SBComposedWallpaperSpecificationColorLayer : SBComposedWallpaperSpecificationLayer {

	UIColor* _color;

}

@property (nonatomic,readonly) UIColor * color;              //@synthesize color=_color - In the implementation block
+(id)colorForLayerDictionary:(id)arg1 ;
+(id)layerWithColor:(id)arg1 ;
-(id)initWithLayerDictionary:(id)arg1 ;
-(id)init;
-(UIColor *)color;
-(id)initWithColor:(id)arg1 ;
-(id)propertyListRepresentation;
@end

