/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBScaleZoomSettings.h>

@class SBAnimationSettings;

@interface SBCrossfadeZoomSettings : SBScaleZoomSettings {

	BOOL _morphWithZoom;
	SBAnimationSettings* _morphSettings;

}

@property (assign) BOOL morphWithZoom;                               //@synthesize morphWithZoom=_morphWithZoom - In the implementation block
@property (retain) SBAnimationSettings * morphSettings;              //@synthesize morphSettings=_morphSettings - In the implementation block
+(id)settingsControllerModule;
-(void)setMorphWithZoom:(BOOL)arg1 ;
-(BOOL)morphWithZoom;
-(SBAnimationSettings *)morphSettings;
-(id)effectiveMorphAnimationSettings;
-(void)setMorphSettings:(SBAnimationSettings *)arg1 ;
-(void)setDefaultValues;
@end

