/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSHashTable;

@interface SBDateTimeController : NSObject {

	NSDate* _overrideDate;
	NSHashTable* _observers;

}

@property (nonatomic,copy,readonly) NSDate * currentDate; 
@property (nonatomic,copy) NSDate * overrideDate; 
+(id)sharedInstance;
-(void)setOverrideDate:(NSDate *)arg1 ;
-(NSDate *)overrideDate;
-(id)init;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(NSDate *)currentDate;
@end

