/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLeafIcon.h>

@class SBApplicationPlaceholder;

@interface SBDownloadingIcon : SBLeafIcon {

	BOOL _wasUninstalledByUser;
	SBApplicationPlaceholder* _appPlaceholder;

}
+(id)leafIdentifierForApplicationPlaceholderBundleID:(id)arg1 ;
-(id)uninstallAlertBody;
-(id)homescreenIconImage;
-(BOOL)isDownloadingIcon;
-(void)completeUninstall;
-(id)initWithApplicationPlaceholder:(id)arg1 ;
-(void)setUninstalledByUser:(BOOL)arg1 ;
-(void)setApplicationPlaceholder:(id)arg1 ;
-(id)gridCellImage;
-(id)_darkenedIconImageForImage:(id)arg1 ;
-(BOOL)uninstalledByUser;
-(id)realDisplayName;
-(void)reloadForStatusChange;
-(id)appPlaceholder;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)cancelDownload;
@end

