/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SoftwareUpdateServices/SUDescriptor.h>

@interface SBFakeSUDescriptor : SUDescriptor
-(id)documentation;
-(BOOL)isDownloadable;
-(unsigned long long)downloadSize;
-(id)productVersion;
-(int)updateType;
-(id)humanReadableUpdateName;
-(unsigned long long)installationSize;
-(unsigned long long)preparationSize;
-(BOOL)isDownloadableOverCellular;
-(id)publisher;
-(id)productBuildVersion;
-(id)productSystemName;
@end

