/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:53 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class CPLRUDictionary;

@interface SBGestureViewVendor : NSObject {

	CPLRUDictionary* m_cache;

}
+(id)sharedInstance;
-(void)clearCacheForReason:(id)arg1 ;
-(void)clearCacheForApp:(id)arg1 reason:(id)arg2 ;
-(id)viewForApp:(id)arg1 gestureType:(unsigned)arg2 includeStatusBar:(char)arg3 ;
-(id)viewForApp:(id)arg1 gestureType:(unsigned)arg2 includeStatusBar:(char)arg3 decodeImage:(char)arg4 ;
-(void)maskViewIfNeeded:(id)arg1 gestureType:(unsigned)arg2 viewType:(int)arg3 contextHostViewRequester:(id)arg4 app:(id)arg5 ;
-(void)dealloc;
-(id)init;
@end

