/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBIconBadgeView.h>
#import <libobjc.A.dylib/_UISettingsKeyObserver.h>

@class SBFParallaxSettings, NSString;

@interface SBIconParallaxBadgeView : SBIconBadgeView <_UISettingsKeyObserver> {

	SBFParallaxSettings* _parallaxSettings;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id)init;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2 ;
-(void)_applyParallaxSettings;
@end

