/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SBFolder, NSString;

@interface SBIconPreviousLocationInfo : NSObject {

	SBFolder* _folder;
	NSString* _folderName;

}

@property (assign,nonatomic,__weak) SBFolder * folder;              //@synthesize folder=_folder - In the implementation block
@property (nonatomic,copy) NSString * folderName;                   //@synthesize folderName=_folderName - In the implementation block
-(NSString *)folderName;
-(void)setFolderName:(NSString *)arg1 ;
-(SBFolder *)folder;
-(void)setFolder:(SBFolder *)arg1 ;
@end

