/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIImage.h>
#import <SpringBoard/SBCountedMapValue.h>

@class NSString;

@interface SBIconAccessoryImage : UIImage <SBCountedMapValue> {

	NSString* _countedMapKey;

}

@property (nonatomic,copy) NSString * countedMapKey;                //@synthesize countedMapKey=_countedMapKey - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCountedMapKey:(NSString *)arg1 ;
-(NSString *)countedMapKey;
-(id)initWithImage:(id)arg1 ;
@end

