/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMapTable, SBIconModel;

@interface SBIconPreviousLocationTracker : NSObject {

	NSMapTable* _previousIconLocations;
	SBIconModel* _iconModel;

}

@property (nonatomic,retain) SBIconModel * iconModel;              //@synthesize iconModel=_iconModel - In the implementation block
-(void)captureLocationInfoForIcon:(id)arg1 inModel:(id)arg2 ;
-(id)previousLocationInfoForIcon:(id)arg1 ;
-(SBIconModel *)iconModel;
-(void)setIconModel:(SBIconModel *)arg1 ;
@end

