/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIScrollView.h>

@interface SBIconScrollView : UIScrollView

@property (assign,nonatomic,__weak) id<SBIconScrollViewDelegate> delegate; 
-(BOOL)cancelTouchTracking;
-(void)setContentOffset:(CGPoint)arg1 ;
-(BOOL)_scrollsToMakeFirstResponderVisible;
@end

