/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SBRemoteAlertAdapter;

@interface SBInCallAlertManager : NSObject {

	SBRemoteAlertAdapter* _currentActiveInCallAlert;
	BOOL _endingCallForLockButtonPress;

}

@property (nonatomic,retain) SBRemoteAlertAdapter * currentActiveInCallAlert;                                      //@synthesize currentActiveInCallAlert=_currentActiveInCallAlert - In the implementation block
@property (assign,getter=isEndingCallForLockButtonPress,nonatomic) BOOL endingCallForLockButtonPress;              //@synthesize endingCallForLockButtonPress=_endingCallForLockButtonPress - In the implementation block
+(id)sharedInstance;
-(BOOL)isEndingCallForLockButtonPress;
-(void)maybeLockUIAfterCallEnded;
-(void)setEndingCallForLockButtonPress:(BOOL)arg1 ;
-(SBRemoteAlertAdapter *)currentActiveInCallAlert;
-(void)setCurrentActiveInCallAlert:(SBRemoteAlertAdapter *)arg1 ;
-(void)reactivateAlertFromStatusBarTap;
-(void)reactivateAlertForActivityContinuationWithActivityIdentifier:(id)arg1 ;
-(void)reactivateAlertFromLockScreenWithUIUnlock:(BOOL)arg1 disableAnimatedTransition:(BOOL)arg2 ;
-(void)reactivateAlertForLockButtonPress;
-(id)init;
@end

