/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBSnapshotDataProvider.h>

@class SBSnapshotDataProviderContext, UIScreen, NSString;

@interface SBIOSurfacePNGSnapshotDataProvider : NSObject <SBSnapshotDataProvider> {

	IOSurfaceRef _surface;
	SBSnapshotDataProviderContext* _context;
	char _shouldRotate;
	UIScreen* _screen;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain,readonly) SBSnapshotDataProviderContext * context;              //@synthesize context=_context - In the implementation block
-(id)initWithIOSurfaceRef:(IOSurfaceRef)arg1 screen:(id)arg2 context:(id)arg3 shouldRotate:(char)arg4 ;
-(void)dealloc;
-(SBSnapshotDataProviderContext *)context;
-(id)fetchData;
@end

