/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@class SBApplication, NSString;

@interface SBLaunchAlertItem : SBAlertItem {

	SBApplication* _associatedDisplay;
	int _type;
	NSString* _bundleID;
	BOOL _isDataAlert;
	BOOL _usesCellNetwork;

}
-(id)initWithLaunchAlertType:(int)arg1 dataAlert:(BOOL)arg2 usesCellNetwork:(BOOL)arg3 bundleID:(id)arg4 ;
-(void)setAssociatedWithDisplay:(id)arg1 ;
-(void)_displayDeactivated:(id)arg1 ;
-(id)_customAirplaneModeAlertPrompt;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(id)alertSheet;
-(BOOL)dismissOnLock;
@end

