/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBLockScreenPluginLoader : NSObject
-(Class)_principalClassFromBundleWithName:(id)arg1 ;
-(BOOL)_verifyPrincipalClass:(Class)arg1 fromBundleWithName:(id)arg2 ;
-(id)_pluginControllerFromPrincipalClass:(Class)arg1 ;
-(id)pluginControllerForName:(id)arg1 activationContext:(id)arg2 ;
@end

