/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlert.h>
#import <SpringBoard/SBWallpaperObserver.h>

@protocol SBLogoutProgressDataSource;
@class UIColor, SBPlatformController, SBMultiUserDefaults, UMUser, SBLogoutProgressAlertView, SBLogoutDebugBlockingViewController, NSString;

@interface SBLogoutProgressAlertViewController : SBAlert <SBWallpaperObserver> {

	unsigned long long _backgroundStyle;
	UIColor* _backgroundColor;
	SBPlatformController* _platformController;
	SBMultiUserDefaults* _multiUserDefaults;
	id<SBLogoutProgressDataSource> _dataSource;
	UMUser* _user;
	SBLogoutProgressAlertView* _progressView;
	SBLogoutDebugBlockingViewController* _debugTasksViewController;

}

@property (assign,nonatomic,__weak) id<SBLogoutProgressDataSource> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,readonly) UMUser * user;                                               //@synthesize user=_user - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_updateLegibility;
-(void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2 ;
-(BOOL)wantsCustomBackgroundStyle;
-(long long)customBackgroundStyle;
-(id)alertDisplayViewWithSize:(CGSize)arg1 ;
-(void)prepareForRestart;
-(void)refreshData;
-(id)initWithUserAccount:(id)arg1 ;
-(void)_updateData;
-(BOOL)_supportsDebugUI;
-(void)_updateDebugTasksViewControllerSizeFromSize:(CGSize)arg1 ;
-(UMUser *)user;
-(void)setDataSource:(id<SBLogoutProgressDataSource>)arg1 ;
-(id<SBLogoutProgressDataSource>)dataSource;
-(long long)statusBarStyle;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)deactivate;
-(void)activate;
-(id)_legibilitySettings;
-(BOOL)hasTranslucentBackground;
@end

