/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class UIView, SBFLockScreenDateView, SBUILegibilityView, UILabel, _UILegibilityLabel, SBFakeStatusBarView, _UILegibilitySettings;

@interface SBLockScreenPreviewView : UIView {

	UIView* _wallpaperView;
	SBFLockScreenDateView* _dateView;
	SBUILegibilityView* _cameraView;
	UILabel* _slideToUnlockView;
	_UILegibilityLabel* _slideToUnlockLegibilityLabel;
	SBFakeStatusBarView* _statusBar;
	_UILegibilitySettings* _legibilitySettings;

}
+(id)preview;
-(id)_legibilityPrototypeSettings;
-(void)_layoutSlideToUnlockView;
-(id)initWithFrame:(CGRect)arg1 legibilitySettings:(id)arg2 ;
-(void)_setupWallpaperView;
-(void)_setupDateView;
-(void)_setupSlideToUnlockView;
-(void)_setupCameraView;
-(void)_setupStatusBar;
-(void)_layoutStatusBar;
-(void)_layoutCameraView;
-(void)layoutSubviews;
-(void)_layoutDateView;
-(void)_layoutWallpaperView;
@end

