/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBLockStateAggregator : NSObject {

	unsigned long long _lockState;

}
+(id)sharedInstance;
-(id)_descriptionForLockState:(unsigned long long)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(BOOL)hasAnyLockState;
-(unsigned long long)lockState;
-(void)_updateLockState;
@end

