/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBLockScreenActionContextFactory : NSObject
+(id)sharedInstance;
-(id)lockScreenActionContextForBulletin:(id)arg1 withOrigin:(int)arg2 pluginActionsAllowed:(BOOL)arg3 ;
-(id)lockScreenActionContextForActivityBlock:(/*^block*/id)arg1 ;
-(id)lockScreenActionContextForBulletin:(id)arg1 action:(id)arg2 origin:(int)arg3 pluginActionsAllowed:(BOOL)arg4 context:(id)arg5 completion:(/*^block*/id)arg6 ;
-(id)lockScreenActionContextForAlertItem:(id)arg1 ;
-(id)lockScreenActionContextForCardItem:(id)arg1 ;
-(id)lockScreenActionContextForSnoozedAlarmItem:(id)arg1 ;
-(id)lockScreenActionContextForWidgetRequest:(/*^block*/id)arg1 ;
-(id)lockScreenActionContextForContinuityApp:(id)arg1 withUniqueIdentifier:(id)arg2 andActivityTypeIdentifier:(id)arg3 appSuggestion:(id)arg4 ;
@end

