/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:09 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBLockScreenNotificationListDelegate <NSObject>
@required
-(void)authenticateForNotificationActionWithCompletion:(/*^block*/id)arg1;
-(void)removeCoordinatedPresentingController:(id)arg1;
-(void)addCoordinatedPresentingController:(id)arg1;
-(void)attemptToUnlockUIFromNotification;
-(void)presentFullscreenBulletinAlertWithItem:(id)arg1;
-(void)notificationListBecomingVisible:(BOOL)arg1;
-(void)modifyFullscreenBulletinAlertWithItem:(id)arg1;
-(void)dismissFullscreenBulletinAlertWithItem:(id)arg1;
-(id)lockScreenScrollView;
-(void)bannerEnablementChanged;

@end

