/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBLockScreenNotificationBannerItemFactory : NSObject
+(id)sharedInstance;
-(BOOL)supportsAwayListItem:(id)arg1 ;
-(id)bannerItemWithAwayListItem:(id)arg1 unlockActionHandler:(id)arg2 delegate:(id)arg3 ;
@end

