/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBLockOverlayContext.h>

@interface SBLockScreenPluginOverlayContext : SBLockOverlayContext {

	BOOL _disabledMesaMatching;

}

@property (assign,nonatomic) BOOL disabledMesaMatching;              //@synthesize disabledMesaMatching=_disabledMesaMatching - In the implementation block
-(BOOL)_pluginNeedsOverlay:(id)arg1 ;
-(BOOL)disabledMesaMatching;
-(void)setDisabledMesaMatching:(BOOL)arg1 ;
-(id)initWithPluginName:(id)arg1 pluginController:(id)arg2 lockScreenViewController:(id)arg3 ;
@end

