/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlertView.h>

@class NSMutableSet, UIView, SBLockScreenBatteryChargingView, SBLoginAppContainerOverlayWrapperView, _UILegibilitySettings;

@interface SBLoginAppContainerView : SBAlertView {

	NSMutableSet* _contentHiddenRequesters;
	UIView* _contentView;
	SBLockScreenBatteryChargingView* _batteryChargingView;
	SBLoginAppContainerOverlayWrapperView* _thermalWarningView;
	UIView* _pluginView;
	_UILegibilitySettings* _legibilitySettings;

}

@property (nonatomic,retain) UIView * contentView;                                                    //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) SBLockScreenBatteryChargingView * batteryChargingView;                   //@synthesize batteryChargingView=_batteryChargingView - In the implementation block
@property (nonatomic,retain) SBLoginAppContainerOverlayWrapperView * thermalWarningView;              //@synthesize thermalWarningView=_thermalWarningView - In the implementation block
@property (nonatomic,retain) UIView * pluginView;                                                     //@synthesize pluginView=_pluginView - In the implementation block
@property (nonatomic,retain) _UILegibilitySettings * legibilitySettings;                              //@synthesize legibilitySettings=_legibilitySettings - In the implementation block
-(SBLockScreenBatteryChargingView *)batteryChargingView;
-(void)setBatteryChargingView:(SBLockScreenBatteryChargingView *)arg1 ;
-(void)_showOrHidePluginViewAppropriately;
-(void)setThermalWarningView:(SBLoginAppContainerOverlayWrapperView *)arg1 ;
-(void)setPluginView:(UIView *)arg1 ;
-(void)setContentHidden:(BOOL)arg1 forRequester:(id)arg2 ;
-(SBLoginAppContainerOverlayWrapperView *)thermalWarningView;
-(UIView *)pluginView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(void)setLegibilitySettings:(_UILegibilitySettings *)arg1 ;
-(_UILegibilitySettings *)legibilitySettings;
@end

