/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class NSDate, SBLockScreenTimerDialView, UILabel, _UILegibilityLabel;

@interface SBLockScreenTimerView : UIView {

	NSDate* _endDate;
	SBLockScreenTimerDialView* _timerDial;
	UILabel* _layoutLabel;
	_UILegibilityLabel* _timerLabel;

}
+(id)_timerFont;
+(double)interItemSpacing;
-(void)setTimerHidden:(BOOL)arg1 ;
-(void)updateTimerLabel;
-(void)setLegibilitySettings:(id)arg1 textStrength:(double)arg2 dialStrength:(double)arg3 ;
-(id)_newTimerDialForSettings:(id)arg1 strength:(double)arg2 ;
-(id)_newLegibilityLabelForSettings:(id)arg1 strength:(double)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(double)baselineOffsetFromBottom;
-(void)setEndDate:(id)arg1 ;
@end

