/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:51 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBFolder.h>

@interface SBNewsstandFolder : SBFolder
+(char)isNewsstandFolderClass;
-(char)isNewsstandFolder;
-(char)canAddIcon;
-(id)nodeIdentifier;
-(void)setIsOpen:(char)arg1 ;
-(id)initWithMaxListCount:(unsigned)arg1 maxIconCountInLists:(unsigned)arg2 ;
-(Class)listModelClass;
-(char)shouldRemoveWhenEmpty;
-(char)canRemoveIcons;
-(char)canEditDisplayName;
-(id)icon;
-(void)setDisplayName:(id)arg1 ;
@end

