/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:54 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray, UIImageView, UIView;

@interface SBNewsstandBackgroundView : UIView {

	NSMutableArray* _shelfViews;
	UIImageView* _overlayGradientView;
	UIView* _bottomView;

}
+(float)dockHeightForOrientation:(int)arg1 ;
+(float)baselineForShelfAtIndex:(unsigned)arg1 withOrientation:(int)arg2 ;
+(float)shelfHeightForOrientation:(int)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
@end

