/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SBNewsstand : NSObject
+(void)reloadDefaults;
+(char)newsstandEnabled;
+(char)addManyIcons;
+(id)bundleIDToReplicate;
+(char)newsstandStoreIsAvailable;
+(char)addFakeApps;
+(void)openNewsstandAppStore;
+(char)useInternationalAssets;
+(char)alwaysShowIconLabels;
+(void)_checkStoreSupport;
+(void)_availableStoreItemKindsDidChange:(id)arg1 ;
+(void)_iconVisibilityDidChange:(id)arg1 ;
+(char)_newsstandStoreIsSupported;
+(char)_newsstandStoreIsRestricted;
+(void)_updateStoreAvailability;
+(void)noteAppRestrictionsDidChange;
+(char)disableIconSkew;
+(void)initialize;
+(void)_loadDefaults;
@end

