/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:51 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUserInstalledApplicationIcon.h>

@class SBNewsstandApplication;

@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon {

	SBNewsstandApplication* _fakeApp;

}

@property (nonatomic,retain) SBNewsstandApplication * fakeApp;              //@synthesize fakeApp=_fakeApp - In the implementation block
-(void)launchFromLocation:(int)arg1 context:(id)arg2 ;
-(char)iconAppearsInNewsstand;
-(int)iconFormatForLocation:(int)arg1 ;
-(char)launchEnabled;
-(char)isNewsstandApplicationIcon;
-(id)getGenericIconImage:(int)arg1 ;
-(Class)iconImageViewClassForLocation:(int)arg1 ;
-(char)shouldWarmUp;
-(void)setFakeApp:(SBNewsstandApplication *)arg1 ;
-(SBNewsstandApplication *)fakeApp;
-(void)dealloc;
-(id)initWithApplication:(id)arg1 ;
-(id)application;
@end

