/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:51 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBFolderIcon.h>

@interface SBNewsstandIcon : SBFolderIcon
-(void)launchFromLocation:(int)arg1 context:(id)arg2 ;
-(id)generateIconImage:(int)arg1 ;
-(id)getUnmaskedIconImage:(int)arg1 ;
-(char)isNewsstandIcon;
-(char)hasFolderIconView;
-(id)_newsstandIconImageName;
-(id)_generateImageUsingMask:(char)arg1 ;
-(id)displayName;
-(id)folder;
@end

