/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:51 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBFolderIconListView.h>

@interface SBNewsstandIconListView : SBFolderIconListView {

	float _iconVPaddingPortrait;
	float _topIconInsetPortrait;
	float _iconVPaddingLandscape;
	float _topIconInsetLandscape;

}
+(unsigned)iconColumnsForInterfaceOrientation:(int)arg1 ;
+(unsigned)maxVisibleIconRowsInterfaceOrientation:(int)arg1 ;
+(int)rotationAnchor;
-(float)bottomIconInset;
-(float)sideIconInset;
-(float)verticalIconPadding;
-(float)topIconInset;
-(Class)baseIconViewClass;
-(void)cleanupAfterRotation;
-(void)_updateVisibleIconsFromRow:(unsigned)arg1 toRow:(unsigned)arg2 includeIcon:(id)arg3 layoutIfNeeded:(char)arg4 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)prepareToRotateToInterfaceOrientation:(int)arg1 ;
@end

