/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:56 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/BBRemoteDataProvider.h>

@class BBSectionInfo, NSExtension, NSString, BBSectionIcon;

@interface SBNotificationCenterDataProvider : NSObject <BBRemoteDataProvider> {

	BBSectionInfo* _sectionInfo;
	NSExtension* _extension;
	NSString* _sectionDisplayName;
	BBSectionIcon* _sectionIcon;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)notificationCenterDataProviderWithSectionInfo:(id)arg1 extension:(id)arg2 ;
+(char)isIconForSectionPrecomposed:(id)arg1 ;
-(id)initWithSectionInfo:(id)arg1 extension:(id)arg2 ;
-(void)_invalidateCachedValues;
-(void)dealloc;
-(id)sortDescriptors;
-(id)sectionIdentifier;
-(id)defaultSectionInfo;
-(id)sectionDisplayName;
-(id)sectionIcon;
-(id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2 ;
@end

