/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:53 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBDefaultDateLabel.h>
#import <SpringBoard/SBRelativeDateTimerDelegate.h>

@class SBRelativeDateTimer, NSString;

@interface SBRelativeDateLabel : SBDefaultDateLabel <SBRelativeDateTimerDelegate> {

	SBRelativeDateTimer* _relativeDateTimer;
	unsigned _value;
	int _resolution;
	int _comparedToNow;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)timerFiredWithValue:(unsigned)arg1 forResolution:(int)arg2 comparedToNow:(int)arg3 ;
-(void)setTimeZoneRelativeStartDate:(id)arg1 absoluteStartDate:(id)arg2 ;
-(id)constructLabelString;
-(void)dealloc;
-(void)prepareForReuse;
@end

