/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:53 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBRelativeDateTimerDelegate;
@class NSCalendar, NSTimer, NSDate;

@interface SBRelativeDateTimer : NSObject {

	NSCalendar* _gregorian;
	NSTimer* _timer;
	NSDate* _date;
	id<SBRelativeDateTimerDelegate> _delegate;
	int _currResolution;
	int _currValue;

}
+(void)invalidateTimer:(id)arg1 ;
+(void)addTimerToMainRunLoop:(id)arg1 ;
+(void)initialize;
-(void)_fireForEvent:(id)arg1 ;
-(void)_fireForLocaleEvent:(id)arg1 ;
-(void)fireAndSchedule;
-(void)_fireAndUpdateTimerIfNecessary;
-(id)_timeDifferenceFromDate:(id)arg1 ;
-(double)_nextFireInterval:(id)arg1 resolution:(int)arg2 comparedToNow:(int)arg3 ;
-(double)nextFireInterval;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(void)invalidate;
-(id)date;
-(void)setDate:(id)arg1 ;
@end

