/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:44 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBReachabilityTrigger.h>

@class NSTimer;

@interface SBReachabilityTapTrigger : SBReachabilityTrigger {

	NSTimer* _tapToTapExpirationTimer;
	NSTimer* _pendingDebounceTimer;
	char _debouncedHome;
	NSTimer* _debounceTimer;
	char _debounced;
	unsigned _numberOfTaps;
	unsigned _currentNumberOfTaps;
	char _reachabilityWasTriggered;

}

@property (assign,nonatomic) unsigned numberOfTaps;              //@synthesize numberOfTaps=_numberOfTaps - In the implementation block
-(void)clearPendingReachabilityTrigger;
-(void)_clearDebounceTimer;
-(void)_clearPendingDebounceTimer;
-(void)_setPendingDebounceTimer;
-(void)_setDebounceTimer;
-(void)_expirationTimerFired:(id)arg1 ;
-(void)_clearPendingTimerFired:(id)arg1 ;
-(void)_debounceTimerFired:(id)arg1 ;
-(void)_setExpirationTimer;
-(unsigned)numberOfTaps;
-(void)setNumberOfTaps:(unsigned)arg1 ;
-(void)dealloc;
-(void)_clearExpirationTimer;
-(void)biometricEventMonitor:(id)arg1 handleBiometricEvent:(unsigned)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
@end

