/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface SBRootFolderDockAnimationViewController : UIViewController {

	long long _forcedInterfaceOrientation;

}

@property (assign,nonatomic) long long forcedInterfaceOrientation;              //@synthesize forcedInterfaceOrientation=_forcedInterfaceOrientation - In the implementation block
-(void)setForcedInterfaceOrientation:(long long)arg1 ;
-(long long)forcedInterfaceOrientation;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
@end

