/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:54 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@class SBSceneManager;

@interface SBSceneLayoutManager : NSObject {

	SBSceneManager* _manager;

}

@property (nonatomic,readonly) SBSceneManager * manager;              //@synthesize manager=_manager - In the implementation block
-(CGRect)frameForDisplayItem:(id)arg1 inLayout:(id)arg2 ;
-(void)dealloc;
-(SBSceneManager *)manager;
-(id)initWithManager:(id)arg1 ;
@end

