/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:48 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SBScreenShotter : NSObject {

	char _writingScreenshot;
	unsigned _screenshotWriteCount;

}
+(id)sharedInstance;
-(char)_isWritingSnapshot;
-(void)_incrementWriteCount;
-(void)finishedWritingScreenshot:(id)arg1 didFinishSavingWithError:(id)arg2 context:(void*)arg3 ;
-(void)finishedWritingCarScreenshot:(id)arg1 didFinishSavingWithError:(id)arg2 context:(void*)arg3 ;
-(void)_decrementWriteCount;
-(void)saveScreenshot:(char)arg1 ;
@end

