/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@interface SBSceneDimmingView : UIView {

	long long _dimmingLevel;

}

@property (assign,nonatomic) long long dimmingLevel;              //@synthesize dimmingLevel=_dimmingLevel - In the implementation block
-(long long)dimmingLevel;
-(void)setDimmingLevel:(long long)arg1 ;
@end

