/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBScreenshotManagerDataSource.h>

@protocol SBScreenshotManagerDataSource <NSObject>
@required
-(id)screenshotManagerDefaultScreensToScreenshot:(id)arg1;

@end


@class NSString;

@interface SBScreenshotManagerDataSource : NSObject <SBScreenshotManagerDataSource>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)screenshotManagerDefaultScreensToScreenshot:(id)arg1 ;
@end

