/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:45 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBSearchResultsViewControllerAction.h>
#import <SpringBoard/SBSearchResultDetailsViewControllerDelegate.h>

@class NSLayoutConstraint, NSString;

@interface SBSearchResultsDetailsViewControllerAction : SBSearchResultsViewControllerAction <SBSearchResultDetailsViewControllerDelegate> {

	NSLayoutConstraint* _leftMargin;
	NSLayoutConstraint* _rightMargin;
	NSLayoutConstraint* _topMargin;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)viewControllerClass;
-(id)performWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)cancelAnimated:(char)arg1 withCompletionBlock:(/*^block*/id)arg2 ;
-(void)updateConstraintConstants;
-(void)searchResultDetailsViewController:(id)arg1 openURLs:(id)arg2 fromCardType:(id)arg3 ;
-(void)dealloc;
-(void)cancel:(id)arg1 ;
@end

