/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:46 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBSearchParsecSimpleCell.h>

@class UIImageView;

@interface SBSearchParsecSimpleChevronCell : SBSearchParsecSimpleCell {

	UIImageView* _chevronView;

}

@property (nonatomic,retain) UIImageView * chevronView;              //@synthesize chevronView=_chevronView - In the implementation block
+(char)supportsSection:(id)arg1 result:(id)arg2 ;
-(id)rightViewFrom:(id)arg1 ;
-(UIImageView *)chevronView;
-(void)setChevronView:(UIImageView *)arg1 ;
-(id)constantConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

