/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:57 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface SBSearchWikiRowSingleCell : UITableViewCell {

	UILabel* _label;

}

@property (assign) UILabel * label;              //@synthesize label=_label - In the implementation block
-(UILabel *)label;
-(void)setLabel:(UILabel *)arg1 ;
@end

