/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:46 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBSearchParsecCell.h>

@interface SBSearchParsecSimpleCell : SBSearchParsecCell
+(char)supportsSection:(id)arg1 result:(id)arg2 ;
-(void)updateWithSection:(id)arg1 result:(id)arg2 traitCollection:(id)arg3 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

