/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlert.h>

@interface SBSIMLockEntryAlert : SBAlert {

	long long _status;

}
-(id)alertDisplayViewWithSize:(CGSize)arg1 ;
-(id)lockEntryView;
-(BOOL)_forcesPortraitOrientation;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)deactivate;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)activate;
-(long long)status;
-(BOOL)hasTranslucentBackground;
@end

