/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBSideSwitcherScrollingItemViewDelegate <NSObject>
@required
-(id)sideSwitcherScroller:(id)arg1 viewForDisplayItem:(id)arg2;
-(void)sideSwitcherScroller:(id)arg1 purgeView:(id)arg2;
-(CGSize*)sideSwitcherScrollerItemSize:(id)arg1;
-(double)sideSwitcherScrollerDistanceBetweenItems:(id)arg1;
-(BOOL)sideSwitcherScroller:(id)arg1 displayItemWantsToBeKeptInViewHierarchy:(id)arg2;

@end

