/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBPasscodeEntryAlertViewController.h>
#import <SpringBoard/SBPasscodeEntryAlertViewDelegate.h>
#import <SpringBoard/SBUIPasscodeLockViewDelegate.h>

@protocol SBPasscodeEntryAlertViewControllerDelegate;
@class SUDocumentation, NSString, SUAutoInstallOperation, UINavigationController;

@interface SBSoftwareUpdateAuthenticationAlertViewController : SBPasscodeEntryAlertViewController <SBPasscodeEntryAlertViewDelegate, SBUIPasscodeLockViewDelegate> {

	/*^block*/id _completionBlock;
	SUDocumentation* _documentation;
	NSString* _passcode;
	SUAutoInstallOperation* _installOperation;
	unsigned long long _installType;
	UINavigationController* _termsAndConditionsController;
	BOOL _showingTermsAndConditions;
	BOOL _isN94;
	id<SBPasscodeEntryAlertViewControllerDelegate> _delegate;

}

@property (nonatomic,copy) id completion;                                    //@synthesize completionBlock=_completionBlock - In the implementation block
@property (nonatomic,readonly) SUDocumentation * documentation;              //@synthesize documentation=_documentation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)alertDisplayViewWithSize:(CGSize)arg1 ;
-(BOOL)suppressesBanners;
-(BOOL)suppressesNotificationCenter;
-(BOOL)suppressesControlCenter;
-(BOOL)suppressesSiri;
-(void)setVisible:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)_sendDeactivationResponseFailureIfNecessary;
-(void)_dismissTermsAndConditionsIfNecessaryAnimated:(BOOL)arg1 withCompletion:(/*^block*/id)arg2 ;
-(BOOL)_shouldShowPasscodeView;
-(void)_presentTermsAndConditionsOrDismissAfterDelay:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)_configurePasscodeView:(id)arg1 ;
-(void)_dismissSelf:(BOOL)arg1 ;
-(void)_presentTermsAndConditions:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_termsAgree;
-(void)_sendCompletionResponse:(BOOL)arg1 ;
-(BOOL)passcodeAlertViewShouldShowAutomaticallyWhenVisible:(id)arg1 ;
-(id)initWithDocumentation:(id)arg1 withInstallType:(unsigned long long)arg2 withInstallOperation:(id)arg3 ;
-(void)_authenticationCancelled;
-(void)_authenticationSuccess:(id)arg1 fromMesa:(BOOL)arg2 ;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(id)delegate;
-(id)completion;
-(void)setCompletion:(id)arg1 ;
-(void)deactivate;
-(SUDocumentation *)documentation;
-(void)_termsDisagree;
@end

