/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/_UISettings.h>

@interface SBSpotlightSettings : _UISettings {

	BOOL _enableSpotlightHomeScreenGesture;
	BOOL _enableSpotlightOnMinusPage;

}

@property (assign,nonatomic) BOOL enableSpotlightHomeScreenGesture;              //@synthesize enableSpotlightHomeScreenGesture=_enableSpotlightHomeScreenGesture - In the implementation block
@property (assign,nonatomic) BOOL enableSpotlightOnMinusPage;                    //@synthesize enableSpotlightOnMinusPage=_enableSpotlightOnMinusPage - In the implementation block
+(id)settingsControllerModule;
-(void)setEnableSpotlightHomeScreenGesture:(BOOL)arg1 ;
-(void)setEnableSpotlightOnMinusPage:(BOOL)arg1 ;
-(BOOL)enableSpotlightHomeScreenGesture;
-(BOOL)enableSpotlightOnMinusPage;
-(void)setDefaultValues;
@end

