/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBFolderController.h>

@interface SBStarkFolderController : SBFolderController {

	unsigned long long _interactionAffordances;
	BOOL _supportsKnobEvents;
	BOOL _supportsTouchEvents;

}

@property (assign,nonatomic) unsigned long long interactionAffordances; 
-(unsigned long long)interactionAffordances;
-(void)setInteractionAffordances:(unsigned long long)arg1 ;
-(void)setInnerFolderController:(id)arg1 ;
-(id)_iconPageIndicatorImageSetCache;
-(Class)_contentViewClass;
@end

