/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBIconListPageControl.h>

@interface SBStarkIconListPageControl : SBIconListPageControl {

	double _scale;

}

@property (assign,nonatomic) double scale;              //@synthesize scale=_scale - In the implementation block
-(id)_iconListIndicatorImage:(BOOL)arg1 ;
-(void)setScale:(double)arg1 ;
-(double)scale;
-(double)_indicatorSpacing;
@end

