/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:07 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBAlertAdapter.h>

@interface SBStarkRelockUIAlert : SBAlertAdapter {

	BOOL _animatingDismiss;

}
-(BOOL)shouldPendAlertItemsWhileActive;
-(id)_animationFactory;
-(void)_animateDismiss;
-(void)_dismissAndLock;
-(void)dealloc;
-(id)init;
-(void)deactivate;
-(void)activate;
-(id)initWithViewController:(id)arg1 ;
-(BOOL)handleMenuButtonTap;
-(BOOL)handleMenuButtonDoubleTap;
-(BOOL)handleMenuButtonHeld;
-(BOOL)hasTranslucentBackground;
-(void)handleAutoLock;
-(BOOL)handleLockButtonPressed;
@end

