/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBStatusBarAlphaChangeDelegate;
@interface SBStatusBarAlphaChangeAssertion : NSObject {

	double _alpha;
	unsigned long long _level;
	id<SBStatusBarAlphaChangeDelegate> _delegate;

}

@property (assign,nonatomic) double alpha;                                                    //@synthesize alpha=_alpha - In the implementation block
@property (nonatomic,readonly) unsigned long long level;                                      //@synthesize level=_level - In the implementation block
@property (assign,nonatomic,__weak) id<SBStatusBarAlphaChangeDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)assertionWithLevel:(unsigned long long)arg1 alpha:(double)arg2 ;
-(id)initWithDelegate:(id)arg1 level:(unsigned long long)arg2 alpha:(double)arg3 ;
-(void)setDelegate:(id<SBStatusBarAlphaChangeDelegate>)arg1 ;
-(void)dealloc;
-(double)alpha;
-(void)setAlpha:(double)arg1 ;
-(id)description;
-(id<SBStatusBarAlphaChangeDelegate>)delegate;
-(void)invalidate;
-(unsigned long long)level;
@end

