/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:04 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBLaunchAlertItem.h>

@interface SBTelephonyAirplaneModeAlertItem : SBLaunchAlertItem {

	BOOL _wasDeviceLocked;

}

@property (assign,nonatomic) BOOL wasDeviceLocked;              //@synthesize wasDeviceLocked=_wasDeviceLocked - In the implementation block
-(void)setWasDeviceLocked:(BOOL)arg1 ;
-(BOOL)wasDeviceLocked;
-(BOOL)reappearsAfterLock;
-(BOOL)dismissOnLock;
@end

