/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:08 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@protocol SBThermalWarningAlertItemDelegate;
@interface SBThermalWarningAlertItem : SBAlertItem {

	id<SBThermalWarningAlertItemDelegate> _delegate;
	int _actionTaken;

}

@property (getter=isWaitingForResponse,nonatomic,readonly) BOOL waitingForResponse; 
-(void)_tryToSendAction:(int)arg1 ;
-(void)_autoCoolDown;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
-(void)_playPresentationSound;
-(BOOL)undimsScreen;
-(BOOL)unlocksScreen;
-(BOOL)isWaitingForResponse;
-(void)didDeactivateForReason:(int)arg1 ;
-(void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2 ;
-(void)willActivate;
@end

