/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:05 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBTodayTableDateHeaderFactory : NSObject
+(id)languagesSupportingDateOrdinals;
-(id)dateFormatForLocale:(id)arg1 singleLine:(BOOL)arg2 ;
-(BOOL)isDateOrdinalSupportedForLocale:(id)arg1 ;
-(id)dateHeaderWithDate:(id)arg1 locale:(id)arg2 singleLine:(BOOL)arg3 ;
@end

