/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 3, 2017 at 12:02:06 AM China Standard Time
* Operating System: Version 9.3 (Build 13E233)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBPolygon.h>

@interface SBTouchTemplate : SBPolygon
-(unsigned long long)matchesPolygon:(id)arg1 matchTransformsAllowed:(unsigned long long)arg2 acceptanceFactor:(double)arg3 outMorphedCandidate:(id*)arg4 ;
@end

