/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:46 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@protocol FBWindowContextAppearance;
@class SBLockScreenViewControllerBase, UIView;

@interface SBUIAnimationPhoneToLockScreenBase : SBUIMainScreenAnimationController {

	SBLockScreenViewControllerBase* _lockScreenViewController;
	UIView*<FBWindowContextAppearance> _contextHostView;
	char _needsScreenDim;

}

@property (setter=_setContextHostView:,getter=_contextHostView,nonatomic,retain) UIView * contextHostView;              //@synthesize contextHostView=_contextHostView - In the implementation block
-(void)_prepareAnimation;
-(id)_lockScreenViewController;
-(id)_contextHostView;
-(void)_noteAnimationDidFinish;
-(id)_getTransitionWindow;
-(char)_shouldHideContextHostViewStatusBar;
-(void)_cleanupAnimation;
-(id)initWithLockScreenController:(id)arg1 deactivatingApp:(id)arg2 ;
-(void)_setContextHostView:(id)arg1 ;
-(void)dealloc;
-(void)_setHidden:(char)arg1 ;
@end

