/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:55 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIAnimationZoomDownApp.h>

@interface SBUIAnimationZoomDownAppToPhone : SBUIAnimationZoomDownApp {

	char _usingSuperZoomImplementation;
	char _fromPhoneAppToFaceTimeAppDuringCall;

}
-(void)animateZoomWithCompletion:(/*^block*/id)arg1 ;
-(void)_prepareAnimation;
-(void)_cleanupAnimation;
-(id)_animationProgressDependency;
-(void)_applicationDependencyStateChanged;
-(char)_waitsForApplicationActivationIfNecessary;
-(id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(char)arg1 endStyleRequest:(id)arg2 endOrientation:(int)arg3 ;
-(void)_cleanupPhonesContextHostView;
-(char)_shouldZoomUsingSuperImplementation;
-(void)_startAnimation;
-(void)dealloc;
@end

