/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIAnimationController.h>
#import <SpringBoard/SBUIAnimationControllerObserver.h>

@class NSMutableArray, NSArray, NSString;

@interface SBUIAnimationControllerGroup : SBUIAnimationController <SBUIAnimationControllerObserver> {

	NSMutableArray* _animations;
	char _finished;

}

@property (nonatomic,readonly) NSArray * animations;                //@synthesize animations=_animations - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)animationController:(id)arg1 willBeginAnimation:(char)arg2 ;
-(void)animationControllerDidFinishAnimation:(id)arg1 ;
-(char)_willAnimate;
-(char)waitingToStart;
-(void)endAnimation;
-(id)initWithAnimations:(id)arg1 ;
-(void)_forEachAnimation:(/*^block*/id)arg1 ;
-(void)_startAnimation;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(void)addAnimation:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(NSArray *)animations;
-(void)addObserver:(id)arg1 ;
-(void)beginAnimation;
@end

