/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:59 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@class SBRemoteAlertAdapter, SBAlertManager, SBIconAnimator;

@interface SBUIAnimationZoomUpInCallAlertFromHome : SBUIMainScreenAnimationController {

	SBRemoteAlertAdapter* _alert;
	SBAlertManager* _alertManager;
	SBIconAnimator* _iconAnimator;

}
-(void)_prepareAnimation;
-(void)_cleanupAnimation;
-(id)initWithAlert:(id)arg1 andAlertManager:(id)arg2 ;
-(void)_startAnimation;
-(void)dealloc;
@end

