/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:55 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@class UIView, SBApplication;

@interface SBUIStaticAnimationController : SBUIMainScreenAnimationController {

	UIView* _staticAppView;
	UIView* _hostView;

}

@property (nonatomic,retain,readonly) SBApplication * app; 
-(void)_prepareAnimation;
-(void)_cleanupAnimation;
-(void)_setupStartDependencies;
-(id)_animationProgressDependency;
-(void)_applicationDependencyStateChanged;
-(char)_shouldDismissBanner;
-(char)_willAnimate;
-(void)_hideAppHostView;
-(id)initWithApp:(id)arg1 ;
-(void)_startAnimation;
-(void)dealloc;
-(SBApplication *)app;
@end

