/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIAnimationController.h>

@interface SBUIMainScreenAnimationController : SBUIAnimationController {

	char _needsToClearBulletinWindowOrientation;

}
-(id)initWithActivatingApp:(id)arg1 deactivatingApp:(id)arg2 ;
-(void)_noteAnimationDidCommit:(char)arg1 withDuration:(double)arg2 afterDelay:(double)arg3 ;
-(id)_getTransitionWindow;
-(void)_cleanupAnimation;
-(void)_dismissBannerAnimated:(char)arg1 ;
-(void)_removeWallpaperAnimationPriorityWithFactory:(id)arg1 ;
-(char)_shouldDismissBanner;
-(void)__startAnimation;
-(void)_clearBulletinWindowOverrideOrientationIfNecessary;
-(void)dealloc;
-(void)beginAnimation;
@end

