/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:55 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@class SBAlertManager, SBAlert, UIView;

@interface SBUIAnimationFadePluginAlertToHome : SBUIMainScreenAnimationController {

	SBAlertManager* _alertManager;
	SBAlert* _alert;
	UIView* _viewToAnimate;

}
-(double)animationDelay;
-(void)_prepareAnimation;
-(void)_cleanupAnimation;
-(id)initWithDeactivatingAlert:(id)arg1 alertManager:(id)arg2 ;
-(void)_startAnimation;
-(void)dealloc;
-(double)animationDuration;
@end

