/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@class SBAlert, SBRemoteAlertAdapter, SBAlertManager;

@interface SBUIAnimationFadeAlertToRemoteAlert : SBUIMainScreenAnimationController {

	SBAlert* _fromAlert;
	SBRemoteAlertAdapter* _remoteAlert;
	SBAlertManager* _alertManager;
	char _initialFakeStatusBarNeeded;
	double _animationDuration;

}
-(void)_prepareAnimation;
-(void)_cleanupAnimation;
-(void)_animationFinished;
-(id)initWithAlert:(id)arg1 toAlert:(id)arg2 alertManager:(id)arg3 ;
-(void)_startAnimation;
-(void)dealloc;
-(double)animationDuration;
@end

