/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:57 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBUIRemoteAlertHostInterface
@required
-(void)setShouldDismissOnUILock:(char)arg1;
-(void)setDesiredHardwareButtonEvents:(int)arg1;
-(void)setDismissalAnimationStyle:(int)arg1;
-(void)setSupportedInterfaceOrientationOverride:(unsigned)arg1;
-(void)setDesiredAutoLockDuration:(double)arg1;
-(void)setAllowsBanners:(char)arg1;
-(void)dismiss;
-(void)setIdleTimerDisabled:(char)arg1 forReason:(id)arg2;
-(void)dismissAndLockUIIfNecessary;
-(void)setAllowsMenuButtonDismissal:(char)arg1;
-(void)setAllowsAlertStacking:(char)arg1;
-(void)setDesiredStatusBarStyleOverrides:(int)arg1;
-(void)setStatusBarHidden:(char)arg1 withDuration:(double)arg2;
-(void)setShouldDisableFadeInAnimation:(char)arg1;
-(void)setWallpaperTunnelActive:(char)arg1;
-(void)setBackgroundStyle:(int)arg1 withDuration:(double)arg2;

@end

