/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:46 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlert.h>

@class NSTimer;

@interface SBUSSDAlert : SBAlert {

	unsigned _receivedString : 1;
	unsigned _dismissOnActivate : 1;
	NSTimer* _delayedDismissTimer;

}
+(void)registerForAlerts;
+(void)_daemonRestart:(id)arg1 ;
+(void)_newSIM:(id)arg1 ;
+(void)registerForSettingsAlerts;
+(id)errorStringForCode:(id)arg1 ;
+(void)test;
-(id)alertDisplayViewWithSize:(CGSize)arg1 ;
-(char)allowsResponse;
-(void)USSDStringAvailable:(id)arg1 allowsResponse:(char)arg2 ;
-(void)_delayedDismiss;
-(char)sentResponse;
-(char)receivedString;
-(void)setDismissOnActivate:(char)arg1 ;
-(void)dealloc;
-(int)statusBarStyle;
-(void)deactivate;
-(void)activate;
@end

