/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:56 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBVibrantBannerView <NSObject>
@required
+(id)defaultColorForElement:(int)arg1;
-(id)colorForElement:(int)arg1;
-(void)setColor:(id)arg1 forElement:(int)arg2;

@end

