/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:54 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SBVoiceControlController : NSObject {

	char _delayedAssistantActivationPending;
	char _headsetDownDelayedActionPerformed;

}
+(char)isVoiceControlVisible;
+(id)sharedInstance;
-(void)configureVoiceControl;
-(void)preheatForMenuButtonWithFireDate:(id)arg1 ;
-(char)handleHomeButtonHeld;
-(void)headsetAvailabilityChanged;
-(void)handleHeadsetButtonDownWithClickCount:(unsigned)arg1 ;
-(char)handleHeadsetButtonUp;
-(char)handleHeadsetButtonUpNotInCall;
-(void)bluetoothDeviceInitiatedVoiceControl:(id)arg1 ;
-(void)bluetoothDeviceEndedVoiceControl:(id)arg1 ;
-(void)_updateNextRecognitionAudioInputPaths:(id)arg1 ;
-(void)_assistantActivationSettingsDidChange:(id)arg1 ;
-(void)_performDelayedHeadsetActionForAssistant;
-(void)_performDelayedHeadsetActionForVoiceControl;
-(void)_prepareDelayedHeadsetAction;
-(void)_cancelDelayedHeadsetAction;
-(id)init;
-(void)_spokenLanguageDidChange:(id)arg1 ;
@end

