/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BaseBoard/BSTransaction.h>

@class SBApplication;

@interface SBWaitForAppActivationTransaction : BSTransaction {

	SBApplication* _application;
	char _manualListener;
	char _done;

}
-(void)noteActivationStateChanged:(int)arg1 ;
-(id)initWithApplication:(id)arg1 manualListener:(char)arg2 ;
-(char)_appStateChanged:(int)arg1 ;
-(void)_activationStateChanged:(id)arg1 ;
-(void)dealloc;
-(void)_didComplete;
-(void)_begin;
-(id)initWithApplication:(id)arg1 ;
@end

