/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:52 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>
#import <SpringBoard/SBModalLayoutCaching.h>

@class SBBBWidgetBulletinInfo, NSString;

@interface SBWidgetBulletinCell : UITableViewCell <SBModalLayoutCaching> {

	SBBBWidgetBulletinInfo* _representedWidgetBulletinInfo;
	int _layoutMode;

}

@property (nonatomic,retain) SBBBWidgetBulletinInfo * representedWidgetBulletinInfo;              //@synthesize representedWidgetBulletinInfo=_representedWidgetBulletinInfo - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) int layoutMode;                                                      //@synthesize layoutMode=_layoutMode - In the implementation block
-(void)setLayoutMode:(int)arg1 ;
-(SBBBWidgetBulletinInfo *)representedWidgetBulletinInfo;
-(void)setRepresentedWidgetBulletinInfo:(SBBBWidgetBulletinInfo *)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(int)layoutMode;
@end

