/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:58 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSMutableArray, NSObject, NSArray;

@interface SBWorkStore : NSObject {

	NSMutableDictionary* _workItemsPerKey;
	NSMutableArray* _keysWithWork;
	NSMutableDictionary* _workExpirationPeriods;
	NSObject*<OS_dispatch_queue> _workQueue;
	unsigned _maxWorkPerKey;
	NSMutableArray* _observers;
	NSObject*<OS_dispatch_queue> _observerQueue;
	double _defaultWorkExpirationPeriod;

}

@property (nonatomic,readonly) NSArray * keysWithWork; 
@property (assign,nonatomic) double defaultWorkExpirationPeriod;                   //@synthesize defaultWorkExpirationPeriod=_defaultWorkExpirationPeriod - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * workItemsPerKey;              //@synthesize workItemsPerKey=_workItemsPerKey - In the implementation block
@property (nonatomic,readonly) NSMutableArray * observers;                         //@synthesize observers=_observers - In the implementation block
@property (nonatomic,readonly) unsigned maxWorkPerKey;                             //@synthesize maxWorkPerKey=_maxWorkPerKey - In the implementation block
-(void)_workQueue_expireWorkForKey:(id)arg1 ;
-(void)_notifyObserversWorkDidChange;
-(id)dequeueWorkForKey:(id)arg1 ;
-(id)initWithMaximumNumberOfWorkItemsPerKey:(unsigned)arg1 ;
-(NSArray *)keysWithWork;
-(void)addWorkItem:(id)arg1 forKey:(id)arg2 ;
-(void)purgeWorkForKey:(id)arg1 ;
-(void)setWorkExpirationPeriod:(double)arg1 forKey:(id)arg2 ;
-(double)defaultWorkExpirationPeriod;
-(void)setDefaultWorkExpirationPeriod:(double)arg1 ;
-(NSMutableDictionary *)workItemsPerKey;
-(unsigned)maxWorkPerKey;
-(void)dealloc;
-(id)description;
-(id)debugDescription;
-(void)removeObserver:(id)arg1 ;
-(NSMutableArray *)observers;
-(void)addObserver:(id)arg1 ;
@end

