/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:45 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@interface SBZoomView : UIView
+(int)_degreesForRotationFromInterfaceOrientation:(int)arg1 toInterfaceOrientation:(int)arg2 ;
+(int)_degreesForRotationFromOriginalImageOrientation:(int)arg1 toInterfaceOrientation:(int)arg2 ;
+(CGSize)_rotateAndNormalizeSize:(CGSize)arg1 withTransform:(CGAffineTransform)arg2 ;
+(id)_chromeStatusBarImageForInterfaceOrientation:(int)arg1 ;
-(id)_initWithFrame:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(char)_shouldAnimatePropertyWithKey:(id)arg1 ;
@end

