/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:44 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)alertViewCancel:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
-(char)alertViewShouldEnableFirstOtherButton:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;

@end

